const { connect } = require("../app-data-source")
const pizzaEntity = require("../pizzas/pizzas.entity")

const sizes = ["Small","Medium","Large"]
const prices = [10, 12, 13,14,10,17,18,20,25,10,12,15,16]
const pizzaNames = ["Bianca Pizza",
"Cheese Pizza",
"Pizza, Margherita",
"Pizza, Mushroom",
"Pizza, Puttenesca",
"Pizza, Salami Piccante",
"Pizza, White Truffle Meat Sauce",
"Cheese Pizza",
"Hawaiian Pizza",
"Meat Lover Pizza",
"Pizza Sub",
"Super Pizza Sub",
"Veggie Pizza",
"Create Your Own Pizza",
"Cheese Pizza",
"Pepperoni Pizza",
"House Made Pizza",
"Mexican Pizza Dip",
"Pepperoni Pizza",
"Pizza Bagel",
"Pizza Con Uovo Fritto",
"Pizza Margherita",
"Pizza Margherita",
"Pizza Schiacchiata Alla Toscana",
"Pizza Schiacchiata Alla Toscana",
"Pizza Bagel",
"Pizza Bagel",
"Pizza Bagel",
"Pizza Bagel (plain)",
"Pizza Bagel With Mushroom",
"Pizza Bagel With Pepperoni",
"Pizza Bagel With Pepperoni and Mushroom",
"Pizza Con Formaggio",
"Bbq Chicken Pizza",
"Breakfast Pizza",
"Cadillac Pizza",
"Hawaiin Pizza",
"Pesto Chicken Pizza",
"Pizza Bread",
"Southwest Pizza",
"Thai Chicken Pizza",
"Vegetarian Pizza",
"Bbq Pizza",
"Create Your Own Pizza",
"Pizza",
"Tuna Pizza",
"Tuna Pizza",
"Small Pepperoni or Cheese Pizza",
"Bbq Chicken Pizza",
"Cheese Pizza",
"Deluxe Pizza",
"Meat Pizza",
"Vegetable Pizza",
"Cheesy Bread Pizza (full)",
"3 Meat Treat Pizza",
"Deep Dish Pizza",
"Ultimate Supreme Pizza",
"Garden Pizza",
"Margarita Pizza",
"Supreme Pizza",
"White Pizza",
"Pizza Toppings",
"Pizza",
"Sausage Onion Jam Pizza",
"Cheese Pizza",
"Chocolate Chip Pizza",
"B.l.t. Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Margherita Pizza",
"White Pizza",
"Cheese Pizzarito",
"Pizza Slices",
"Pizza Dough Balls",
"Pizza Dough Flats",
"Margherita Pizza",
"Build Your Own Pizza",
"Build Your Own Pizza",
"Cheese Pizza",
"Chicken Wing Pizza",
"Neapolitan Style Pizza",
"Blt Pizza",
"Cheese Pizza",
"Cheese Pizza",
"Cheese Pizza Slice",
"Cheesesteak Stuffed Cheese Pizza",
"Cheesesteak Stuffed Cheese Pizza",
"Chicken Alfredo Pizza",
"Chicken Parmigiana Pizza",
"Chicken Wing Pizza",
"Chicken Wing Pizza",
"Margherita Pizza",
"Margherita Pizza",
"Old Fashion Pizza",
"Old Fashion Pizza",
"Old Fashion Tomato Pizza",
"Old Fashion Tomato Pizza",
"Pizza Fries",
"Pizza Steak Sub",
"Rancher Pizza",
"Rancher Pizza",
"Sicilian Pizza",
"Sicilian Pizza",
"Taco Pizza",
"Taco Pizza",
"Trenton Tomato Pizza",
"Trenton Tomato Pizza",
"White Pizza",
"White Pizza",
"Cheese Pizza",
"Pizza",
"Pizza Skins",
"Half Pizzas",
"M.y.o.p Make Your Own Pizza",
"Make Your Own Pizza",
"Mini Cheese and Tomato Deep Dish Pizza",
"Mini Cheese or Pepperoni Thin Crust Pizza",
"Pizza of The Day",
"Pizza Skins",
"Thin Crust or Deep Dish Pizza",
"Cheese Pizza",
"Chocolate Chip Pizza",
"Byo Pizza",
"Cheese Pizza",
"Pepperoni Pizza",
"Cheese Pizza",
"Rollatini Pizza",
"Pizza Sub",
"Pizza of The Day",
"Kids Size Pizza",
"Brick Oven Pizza Al Metro",
"Fried Pizza",
"Pork Tenderloin Pizzaiola",
"Cheese Pizza",
"Pepperoni Pizza",
"Eggscellent Pizza (white)",
"Mini Pizza",
"Artichoke Chicken Pizza",
"Barbecue Chicken Pizza",
"California Pizza",
"Chicken Club Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Pizza Mia",
"Cheese Steak Pizza",
"Chicken Parmesan Pizza",
"Personal Pizza",
"Vodka Sauce Pizza",
"Pizza Bagel",
"Chinese Pizza",
"Personal Pizza",
"Pizza Bread",
"House Made Pizza",
"Mexican Pizza",
"Pizza Combo",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Californian Pizza",
"Cheese Steak Pizza",
"Greek Pizza",
"Italiano Pizza",
"Margherita Pizza",
"Mediterranean Pizza",
"Monte Carlo Pizza (white)",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Pizza Sub",
"Seafood Pizza",
"Sicilian Pizza",
"Two Slices of Cheese Pizza",
"Two Slices of Cheese Pizza",
"Veggie Lovers Pizza",
"White Pizza",
"Mexican Pizza",
"Pita Pizza",
"Pizza Mexicana",
"Greek Pizza",
"White Pizza",
"White Pizza",
"Pizza Blanca",
"Pizza Bomba",
"Pizza Margherita",
"Chicken Pizza",
"Spicy Buffalo Pizza",
"Baked Ziti Pizza",
"Capelli Pizza",
"Cheesesteak Pizza",
"Chicken Parmigiana Pizza",
"Grandma Pizza",
"Hawaiian Pizza",
"Large Pizza and Mussels",
"Large Pizza Cheese",
"Order 3 Large Pizzas and Get The 4th Pizza Free",
"Primavera Pizza",
"Vegetarian Pizza",
"White Pizza",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Pizza Bread",
"Greek Pizza",
"Pizza Bites",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Pizza Sub",
"Steak Pizza",
"White Pizza",
"Pizza Burger",
"Pizza Fries",
"8 Corner Pizza",
"Pizza",
"Meat Lovers Pizza",
"Cheese Pizza",
"Gourmet Chicken Ranch Pizza",
"Gourmet Meat Pizzatm",
"Mexico City Grill Pizza",
"Mexico City Pizza",
"White Pizza",
"Pizza",
"Pizza Roll",
"Berlin Pizza",
"Pizza Bruschetta",
"Shrimp Scampi Pizza",
"Pizza",
"The Original Bbq Chicken Pizza",
"Taco Pizza",
"Pizza Logs",
"Pizza Logs",
"Buffalo Pizza",
"Cheese Pizza",
"Grilled Chicken Pizza",
"Pizza Burger",
"Pizza Fries",
"Vegetable Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Pepperoni Pizza",
"Pepperoni Pizza",
"Smoked Chicken Bbq Pizza",
"Spinach Artichoke Pizza",
"Wood Fire Grilled Pizza",
"Pizza Steak",
"Garden Pizza",
"Cheese Pizza",
"Gyro Pita Pizza",
"Gyro Pizza",
"Sushi Pizza",
"Pizza Roll",
"Italian, Veggie or Pizza Sub",
"Adult Cheese Pizza",
"Artichoke and Sweet Potato Pizza",
"Tuscan Fig and Oyster Mushroom Pizza",
"Captain Jean Pizza",
"Cheese Pizza",
"Cove Taco Pizza",
"Greek Pizza",
"H.o.g. Pizza",
"Man Eater Mike Pizza",
"Maneater Mike Pizza",
"Pirate Special Pizza",
"Pizza Bread",
"Deluxe Pizza",
"Greek Pizza",
"Pizza By The Slice",
"Pizza Sub",
"Supreme Deluxe Pizza",
"Veggie or Meat Deluxe Pizza",
"White Pizza",
"Broad Street Cheese Pizza",
"Pizza Bianca",
"Vegan Pizza",
"Margarita Flat Bread Pizza",
"Tuna Pizza",
"Bacon Pizzaburger",
"Dessert Pizza",
"Las Pizzas Del Fuego",
"Pizza Rolls",
"The White Pizza",
"White Pizza",
"Buffalo Chicken Pizza",
"Carne Pizza",
"Deluxe Style Pizza",
"Hawaiian Pizza",
"Pepperoni Pizza Steak",
"Pizza Steak",
"Plain Cheese Pizza",
"Primavera Pizza",
"Sicilian Style Pizza",
"Veggie Pizza",
"White Pizza",
"Wood Oven Pizza",
"Cheese Pizza",
"Pizzaroni",
"Taco Pizza",
"Veggie Pizza",
"Large Cheese Pizza.",
"Large Supreme Pizza.",
"Small Cheese Pizza",
"Small Supreme Pizza",
"Great Tasting Cheese Pizza",
"Original Herb Cheese Pizza Points",
"Chicago Classic Deep Dish Pizza",
"Chicken Verde Artisan Crust Pizza",
"Classic Margherita Artisan Crust Pizza",
"Gluten Free Cheese Tomato Thin Crust Pizza",
"Gluten Free Pepperoni Thin Crust Pizza",
"Gluten Free Veggie Thin Crust Pizza",
"Napoli Artisan Crust Pizza",
"Pizza Skins",
"Prosciutto Arugula Artisan Crust Pizza",
"Flatbread Pizza of The Day",
"Meatball Pizza",
"Caprese Pizza",
"White Pizza",
"Homemade Mexican Pizza",
"Vegetarian Mexican Pizza",
"Chicken Pizza Steak",
"Pepperoni Chicken Pizza Steak",
"Pepperoni Pizza Burger",
"Pepperoni Pizza Pretzel",
"Pepperoni Pizza Steak",
"Pizza Burger",
"Pizza Fries",
"Pizza Pretzel",
"Pizza Roll",
"Pizza Steak",
"Pizza Roll",
"Pizza Dough",
"Round Pizza By The Slice",
"Taco Pizza",
"Vegetarian Pizza",
"Byop (build Your Own Pizza)",
"Arugula Pizza (seasonal)",
"Autumn Pizza (seasonal)",
"Bronx Bomber Pizza",
"Bruha Pizza",
"Carne Pizza",
"Fennel Pizza (seasonal)",
"Formaggi Pizza",
"Funghi Pizza",
"Margherita Pizza",
"Nutella Pizza",
"Pesto Pizza (seasonal)",
"Chicken Supreme Pizza",
"Loaded Steak Pizza",
"Arthichoke Heart Chicken Pizza",
"Bbq Chicken Pizza",
"Combination Pizza",
"Create Your Own Pizza",
"Fire Den Supreme Pizza",
"Garlic Chicken Pizza",
"Greek Chicken Pizza",
"Hawaiian Pizza",
"Italian Pizza",
"Pesto Chicken Pizza",
"Pesto Sauce Pizza (vegetarian)",
"Pizza Special",
"Vegetarian Pizza",
"Pizza Sub",
"Taco Pizza",
"Spicy Tuna Pizza or Spicy Salmon Pizza",
"Pizza",
"Cheese Pizza",
"Pizza Slice",
"Whole Pizza",
"Famous Paisans Pizza Sauce Quart",
"Four 18 Pizzas",
"Gluten Free Pizza",
"Pizza Fries",
"The Original Cheese Pizza",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"The Reuben Pizza",
"White Pizza",
"Four Pig Pizza",
"Pizza Bread",
"Classic Pepperoni Lahvosh Pizza",
"Blt Pizza",
"Create Your Own Pizza",
"Margherita Pizza",
"Margherita Pizza (on Honey Wheat Dough)",
"New York Style Pizza",
"Philly Cheese Steak Pizza",
"Pizza",
"Rolled Pizza Bites 10",
"Veggie Pizza (on Honey Wheat Dough)",
"Caeser Sald Pizza",
"Caprese Pizza",
"Grandma Pizza (round or Square)",
"Hawaiian Pizza",
"Pizza Primavera",
"Pizza Upside Down",
"Pizza Vodka Sauce",
"Pizza White",
"Regular Chicken Pizza",
"Taco Pizza",
"Pizza Sandwich",
"Pizza",
"Moped Pizza",
"Bacon Cheddar Burger Pizza",
"Create Pizza",
"Howie Maui Pizza",
"Howie Special Pizza",
"Large Pepperoni Plus Pizza",
"Large The Works Pizza",
"Meat Eaters Pizza",
"Medium Cheese Pizza",
"Philly Cheesesteak Pizza",
"Pizza Dipping Sauce Cup",
"Pizza Sub",
"Pizza Sub Deluxe",
"The Works Pizza",
"Veggie Pizza",
"Pizza Fries",
"Cheese Pizza",
"B.b.q. Chicken Pizza",
"Build Your Own Pizza",
"Cheese Pizza",
"French Bread Pizza",
"Gluten Free Veg Out Pizza",
"Hawaiian Pizza",
"Pepperoni Pizza",
"Roasted Vegetable Pizza",
"Spicy Meat Pizza",
"Thai Dye Pizza",
"The Everything Pizza",
"Thin Crust Margarita Pizza",
"Mushroom Hunter Pizza",
"Caprese Pizza",
"Pizza",
"Pizza Marinara",
"Pizza Primavera",
"Pizza Rolls",
"Pizza Toppings",
"Sorrentino Pizza",
"Specialty Pizza Toppings",
"Spinach Pizza",
"White Pizza",
"Meat Lover Pizza",
"New York Style Pizza",
"Pizza By The Slice",
"Pizza By The Slice",
"Pizza Slice",
"Supreme Combo Pizza",
"Veggie Combo Pizza",
"Veggie Supreme Pizza",
"Blast Furnace Pizza",
"Buffalo Chicken Pizza",
"Dark Hollow Pizza",
"Jones Street Pizza",
"Ohio River Pizza",
"Pierogi Pizza",
"Piranha Pizza",
"Plain or Pepperoni Pizza",
"Plain or Pepperoni Pizza",
"Reuben Pizza",
"River Town Pizza",
"Seafood Pizza",
"The Youghigheny Pizza",
"To The Price of Any Pizza",
"Fresh Mushroom Pizza",
"Margherita Pizza",
"Marinara Pizza",
"Napolitana Pizza",
"Pepperoni Pizza",
"Provencal Pizza",
"Romana Pizza",
"Toscana Pizza",
"Tre Colori Pizza",
"Pizza",
"Pizza Sticks",
"Kids Size Pizza",
"Pizza Steak",
"Truffled Egg Pizza",
"Mexican Pizza",
"Fruit Pizza",
"Khans Korean Pizza",
"Pizza Boy Citra Pils (4)",
"Pizza or Calzone",
"Pizza or Calzone",
"Pizza",
"The Original Bbq Chicken Pizza",
"White Pizza",
"1 Topping Pizza",
"1 Topping Pizza",
"2 Toppings Pizza",
"2 Toppings Pizza",
"Cheesy Pita Pizza",
"Blt or Pizza Sub",
"Blt or Pizza Sub",
"Chicken Parmesan Pizza",
"Pizza Logs",
"Stinger Pizza",
"White Pizza Sub",
"Grilled Pizza",
"Pizza Special",
"Marinara Pizza",
"Vegan Margherita Pizza",
"1 Item Pizza",
"2 Items Pizza",
"3 Items Pizza",
"4 or More Items Pizza",
"Cattleman Pizza",
"Cheese Pizza",
"Greek Pizza",
"Moussakka Style Pizza",
"Pesto Pizza",
"Philly Cheese Steak Pizza",
"Primavera Pizza",
"Shrimp Scampi Pizza",
"Stuffed Pizza",
"Taco Pizza",
"Bbq Roasted Chicken Pizza",
"Bella Rossa Pizza",
"Mushroom Fontina Pizza",
"Pizza Margherita",
"Vegetable Pizza",
"Chocolate Chip Pizza",
"Cheese Flatbread Pizza",
"Bbq Chicken Pizza",
"Cheese Pizza",
"Mama Light Pizza",
"Pizza Hoagy",
"Super Veggie Pizza",
"Veggie Special Pizza",
"Pizza Vino Caesar",
"Stuffed Jalapeno Pizza",
"Pepperoni Pizza",
"Pizza Bread Cheese",
"Specialty Pizza",
"Stuffed Pizza Cheese",
"Pizza",
"The Original Bbq Chicken Pizza",
"White Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Pizza Rolls",
"Pizza Slice",
"White Pizza",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Whole Breakfast Pizza",
"Pizza By The Slice",
"Pizza Sub",
"Pizza Bread",
"Pizza Burger",
"Pizza Puff",
"Pizza Bagel",
"Cheese Pizza",
"Chicken Supreme Pizza",
"Create Your Own Pizza",
"Stuffed Pizza Rollers",
"Super Supreme Pizza",
"Supreme Pizza",
"Taco Pizza",
"Veggie Pizza",
"Our Famous Thin Crust Pizza",
"Pizza Ai Fichi",
"Pizza Ai Fichi",
"Pizza Alla Genovese",
"Pizza Alla Genovese",
"Pizza Bianca",
"Pizza Margherita",
"Pizza Quattro Formaggi",
"Pizza Verde",
"Pizza Burger",
"Pizza",
"10 Pizza Margherita",
"Pizza Margherita",
"Mexican Pizza",
"Shrimp Chorizo Pizza",
"Bbq Chicken Pizza",
"I Like Meat Pizza",
"The Flamethrower Pizza",
"Cheese Pizza",
"Carmelized Leek Pizza, Roasted Garlic Soubise, Fingerling Potatoes",
"House Smoked Salmon Pizza, Lemon Creme Fraiche, Tobiko Caviar",
"Mini Cheese Pizza",
"Portabella Mushroom Pizza, Fontina, White Truffle Oil",
"Prosciutto Pizza, Wild Arugula, Fontina, White Truffle Oil",
"Spicy Rock Shrimp Pizza, Roasted Tomato Sauce, Caramelized Leeks",
"Stuffed Pizza Rolls",
"Sushi Pizza",
"Crab Pizza",
"Abbondante Bbq Chicken Pizza",
"Isabella Pizzarella",
"Puttanesca Pizza",
"Hummus Veggie Pizza",
"Quick Gyro Thin Crust Pizza",
"Nutilla Pizza",
"Scaloppine Pizzaiola",
"Scaloppine Pizzaiola",
"Greek Pizza",
"Pizza",
"Cheese Pizza",
"El Diablo Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Pizza Del Giorno",
"Pizza Dujour",
"Pizza Dolce Alla Nutella",
"Italian Herb Pizza Crust",
"Simply Pizza Crust",
"Simply Pizza Crust Mix",
"Arrabbiatta Pizza",
"Broccoli Pizza",
"Buffalo Chicken Pizza",
"Carchiofi Pizza",
"Cheese Pizza",
"Chicken Alfredo Pizza",
"Chicken Cordon Bleu Pizza",
"Chicken Cutlet Pizza",
"Chicken Florentine Pizza",
"Clam Pizza",
"Eggplant Parmesan Pizza",
"Florentine Pizza",
"Genovese Pizza",
"Hawaiian Pizza",
"Hot Wheel Pizza",
"Italian Flag Pizza",
"Italiano Pizza",
"Lasagna Pizza",
"Margherita Pizza",
"Meat Stuffed Pizza",
"Mediterranean Pizza",
"Mona Lisa Pizza",
"Ortolano Pizza",
"Pesto Pizza",
"Seafood Pizza",
"Shrimp Alfredo Pizza",
"Shrimp Scampi Pizza",
"Steak Pizza",
"Tomato, Bacon, and Ranch Pizza",
"Tropical Tease Pizza",
"Vegetarian Pizza",
"Florentine Pizza",
"3 Topping Pizza",
"Cheese Pizzas",
"Perfect Pizza Sub",
"Specialty Pizza",
"Baked Ziti Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Chicken Napolitano Pizza",
"Chicken Parmigiana Pizza",
"Eggplant Rollatini Pizza",
"Everything Pizza",
"Grilled Chicken Vodka Pizza",
"Hawaiian Pizza",
"Italian Pizza",
"Margherita Pizza",
"Pizza Burger",
"Pizza Steak",
"Shrimp Pizza Marinara",
"Veal Pizzaiola",
"Veggie Pizza",
"White Pizza",
"Whole Wheat Pizza",
"Mexican Pizza",
"Morning Pizza",
"Pizza Roll",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Cheesy Pizza",
"Bbq Chicken Pizza",
"Breakfast Pizza",
"Pizza By The Slice",
"Pizza Steak",
"Sicilian Pizza",
"Taco Pizza",
"Veggie Pizza",
"White Pizza",
"Spicy Chicken Pizza",
"2 Pizza Roll",
"Bacon Cheeseburger Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Chicken Alfredo Pizza",
"Chicken Cacciatore Pizza",
"Chicken Fajita Pizza",
"Chicken Special Pizza",
"Greek Pizza",
"Grilled Chicken Pizza",
"Hawaiian Pizza",
"Honey Chicken Pizza",
"Meat Lover Pizza",
"Philly Steak Pizza",
"Pita Pizza",
"Pizza Cheese Burger",
"Pizza Cheese Burger Platter",
"Pizza Fries",
"Pizza Steak",
"Pizza Steak Platter",
"Plain Pizza",
"Plain White Pizza",
"Seafood Pizza Platter",
"Takka Sumpreme Pizza",
"Tomato Pie Pizza",
"Vegetables Pizza",
"Bbq Chicken Pizza",
"Combo Pizza",
"Gluten Free Pizza",
"Lasagna Pizza",
"Margherita Pizza",
"Meat Pizza",
"New York Style Pizza",
"Veggie Pizza",
"White Pizza",
"2 Large Cheese Pizzas",
"2 Medium Cheese Pizzas",
"3 Medium Cheese Pizzas",
"4 Medium Cheese Pizzas",
"Cheese Pizza",
"Nutella Pizza",
"Cheese Pizza",
"Pizza Sauce",
"Cheese Pizza",
"Pepperoni Pizza",
"Supreme Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"California Pizza",
"Chalet Pesto Pizza",
"Chalet Red Hot Pizza",
"Chalet Vegetarian Pizza",
"Hawaiian Pizza",
"Margherita Pizza",
"Parmesan Chicken Pizza",
"Pizza Chalet Mexican Pizza",
"Pizza Chalet Special",
"Pizza Chalet Swiss Combo",
"Teriyaki Chicken Pizza",
"Texas Chicken Pizza",
"Cheese Pizza",
"Pizza Mania",
"Pizza Puffs",
"Pizza Slice",
"Pizza Slice, Fries",
"Miso Pizza",
"Tofu Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Bruschetta Pizza",
"Chicken Parmigiana Pizza",
"Deep Dish Pan Pizza",
"Hawaiin Pizza",
"Large Cheese Pizza",
"Large Pizza",
"Personal Pizza",
"Pizza By The Slice",
"Pizza By The Slice",
"Pizza De Mare",
"Sicilian Pizza",
"Small Cheese Pizza",
"Small Pizza",
"Stuffed Pizza (meat)",
"Stuffed Pizza (vegetable)",
"Toscana Pizza",
"Veal Pizzaiola",
"Vodka Sauce Pizza",
"Cheese Pizza",
"Kids Pizza",
"Pizza Fries",
"Large 4 Topping Pizza",
"Large 4 Topping Pizza",
"Large 6 Toppings Pizza",
"Large 6 Toppings Pizza",
"Medium 4 Topping Pizza",
"Medium 4 Topping Pizza",
"Medium 6 Topping Pizza",
"Medium 6 Topping Pizza",
"Pizza Burger",
"Pizza Burger",
"Pizza Con Formaggio",
"Mexican Pizza",
"Pizza Roll",
"Pizza Abbroz",
"Pizza Barbeque",
"Pizza Carne",
"Pizza Finito",
"Pizza Fresca",
"Pizza Hawaiian",
"Pizza Seafood, White or Red",
"Pizza Stella Notte",
"Plain Cheese Pizza",
"Cheese Pizza",
"Barbeque Pizza",
"Blackened Chicken Caesar Pizza",
"Cheese Pizza",
"Cheese Pizza",
"Pizza Role",
"Enchilada Pizza",
"Mexican Pizza",
"Quesadilla Pizza",
"Taco Pizza",
"Tamale Pizza",
"Taquitos Pizza",
"Flatbread Pizza, Caramelized Onion, Goat Cheese, Wild Mushrooms",
"Flatbread Pizza, Fresh Mozzarella, Basil, Roasted Garlic and Pine Nuts",
"Kids Pizza",
"Pizza of The Week",
"White Pizza (no Sauce)",
"Additional Toppings Cheese Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Dessert Pizza",
"Pizza Bruschetta",
"Slice of Cheese Pizza",
"Thick or Thin Crust Cheese Pizza",
"Pizza",
"Pizza By The Slice",
"Taco Pizza",
"Vegetarian Pizza",
"Thin Grilled Pizza or Thick Crust",
"Thin Grilled Pizza or Thick Crust",
"Pizza Bread",
"Pizza Bread",
"Flatbread Pizza of The Day (yazoo Pale Ale)",
"9th Island Pizza",
"Mexican Pizza",
"White Pizza",
"Cheese Personal Pizza",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Bistecca Alla Pizzaiola",
"Bistecca Alla Pizzaiola",
"Pizza Burger",
"Covaccino Pizza",
"Margarita Pizza",
"Marinara Pizza (tomato Pie)",
"Nutella Pizza",
"White Pizza",
"Breakfast Pizza",
"Breakfast Pizza",
"Greek Pizza",
"Mediterranean Pizza",
"Breakfast Pizza",
"Breakfast Pizza",
"Chicken Teriyaki Flatbread Pizza",
"Chicken Teriyaki Pizza",
"Mozzarella Pizza",
"Pork Pie Flatbread Pizza",
"Veggie Flatbread Pizza",
"10 Inches Pizza Cheese",
"16 Inches Pizza Cheese",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Create Your Own Pizza",
"Veggie Patch Pizza",
"Cheese Pizza",
"Cheese Pizza",
"Bbq Chicken Pizza",
"Broccoli and Tomato Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Meat Lovers Pizza",
"Pizza Burger",
"Pizza Steak",
"Sicilian Cheese Pizza",
"Sicilian Works Pizza",
"Two Brothers Special Pizza",
"White Bacon and Tomato Pizza",
"White Broccoli and Tomato Pizza",
"White Veggie Pizza",
"Works Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Margherita Flatbread Pizza",
"Pesto Chicken and Artichoke Flatbread Pizza",
"Prosciutto and Arugula Flatbread Pizza",
"Wood Oven Cheese Pizza",
"Deep Dish Pizza",
"Junior Pizza",
"Large Pizza",
"Medium Pizza",
"Medium Thin Crust Pizza",
"Pizza Sub",
"Pizza Sub Deluxe",
"Small Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Hawaiian Pizza",
"Marguerita Pizza",
"Staten Island Pizza",
"Veggie Pizza",
"Calabash Island Pizza",
"Calabash Pizza",
"Pizza",
"The Original Bbq Chicken Pizza",
"Flat Bread Pizza",
"Seafood Pizza",
"Seafood Pizza",
"Artichoke Pizza",
"Margherita Pizza",
"Mediterranean Pizza",
"Mushroom Pizza",
"Pepperoni Pizza",
"Spicy Sausage Pizza",
"White Pizza",
"Party Pizza",
"Pizza Bar",
"Pizza Fries",
"Delux Pizza",
"Bbq Pizza",
"Pizza Burger",
"Pizza Puff",
"Scallion Pancakes (chinese Pizza)",
"Pizza Puff",
"1 Topping Pizza",
"Dessert Pizza",
"Mini Pizza",
"Pizza Bread",
"Taco Pizza",
"Pizza Bread Slices",
"With Pizza Cheese",
"Taco Pizza",
"Taco Pizza",
"Pizza Slice",
"Sicilian Cheese Pizza",
"White Pizza",
"Margherita Pizza",
"Margherita Pizza",
"Pizza Tartlets",
"Pizza Tartlets",
"Terra Piparade Pizza",
"Pizza Burger",
"Pizza or Mushroom Hoagie",
"Flatbread Pizza",
"Sushi Pizza",
"4. Pizza Cheese Steak",
"Cheese Pizza",
"Pizza Sub",
"Pizza Sub Wrap",
"Veggie Patch Pizza",
"Cheese Pizza",
"Pepperoni Pizza",
"Chicken, Spinach Bacon Pizza",
"Margherita Pizza",
"Pepperoni Classica Pizza",
"Prosciutto Fennel Pizza",
"Sicilian Pizza",
"Grilled Flatbread Pizza",
"Pizza Burger",
"Good Company Fiesta Pizza",
"Good Company Fiesta Pizza",
"Kickin Chicken Pizza",
"Kickin Chicken Pizza",
"Meat Lovers Pizza",
"Meat Lovers Pizza",
"Wild Ranch Pizza",
"Wild Ranch Pizza",
"Make Your Own Pizza",
"Margherita Pizza",
"Roasted Mushroom Pizza",
"Artichoke Combo Pizza",
"Carnivore Pizza",
"Chicken Gourmet Pizza",
"Chicken Supreme Pizza",
"City Combo Pizza",
"City Special Pizza",
"Gourmet Spinach Pizza",
"Greek Combo Pizza",
"Hawaiian Pizza",
"Pesto Pizza",
"Pizza Sandwich",
"Vegetarian Pizza",
"Pizza Fries",
"St. Elmo Prime Rib Pizza",
"Thin Crust Pizza",
"Pizza",
"Pizza Steak",
"Pizzaiola",
"Z Breakfast Pizza",
"Bbq Chicken Pizza",
"Cheese Pizza",
"Pizza Bagel",
"Pizza Bianco",
"Pizza By The Slice",
"Pizza Toppings",
"Pizza Bagel",
"Steak Pizzaiola",
"Garlic Pizza",
"White Pizza",
"Create Your Own Pizza",
"Pizzawich Monster Sub",
"Plain Cheese Pizza",
"Pizza Puff",
"Cheese Flatbread Pizza",
"Margherita Pizza",
"Margherita Pizza, Tomatoes, Mozzarella and Basil",
"Wild Mushroom Pizza",
"Caprese Pizza",
"Greek Pizza",
"Veggie Pizza",
"White Pizza",
"Works Pizza",
"Cheese Pizza",
"Broccoli Pizza",
"Cheese Pizza",
"Chicken Pizza",
"Chicken With Broccoli Pizza",
"Eggplant Pizza",
"Fresh Tomatoes Pizza",
"Hawaiian Pizza",
"Meat Lover Pizza",
"Meatball Pizza",
"Mushroom Pizza",
"Onion Pizza",
"Pepperoni Pizza",
"Peppers Pizza",
"Pizza Slice",
"Sausage Pizza",
"Spinach Pizza",
"Veggie Pizza",
"White Pizza",
"Whole Wheat Veggie Pizza",
"Greek Pizza",
"Brunch Pizza",
"Scaloppine Di Pollo Alla Pizzaiola",
"Dessert Pizza",
"Hawaiian Pizza",
"Meat Supreme Pizza",
"Pizza",
"Pizza Hoagie",
"Pizza Bagel",
"Cave Man Pizza",
"Cheese Pizza",
"Marino Pizza",
"Veggie Pizza",
"Virgin White Pizza",
"Greek Pizza",
"White Pizza",
"Cheese Pizza",
"City Pizza",
"Margherita Pizza",
"Not Just Your Regular Veggie Pizza",
"Pepperoni Pizza Poppers",
"Phat Boyz White Pizza",
"Philly Cheesesteak Pizza",
"Philly Cheesesteak Pizza Rolls",
"Pizza Taco Roll",
"Super Spud Pizza",
"Taco Pizza",
"Pepperoni Pizza",
"Pepperoni Pizza",
"Pizza Margherita",
"Pizza Margherita",
"Pizza Special",
"Pizza Special",
"Prime Rib Pizza",
"Prime Rib Pizza",
"Specialty Pizza, Preparations Change",
"Specialty Thin Crust Pizza",
"Margarita Pizza",
"Pint of Pizza Sauce",
"Pizza Steak",
"Side of Pizza Sauce",
"Stuffed Deluxe Pizza",
"Bella Pizza",
"Five Cheese Pizza",
"Hawaiian Pizza",
"Mexican Pizza",
"Pizza Boat",
"Seafood Pizza",
"Steak Pizza",
"Traditional Cheese Pizza",
"Vegetable Pizza",
"Mexican Pizza",
"2 Med Pizzas",
"French Bread Pizza",
"Pizza Bagel",
"Pizza Bread",
"Pizza Calzones",
"Blt Pizza",
"Breakfast Pizza",
"Heirloom Tomato Pizza",
"Pulled Chicken Pizza",
"Barbecue Chicken Flatbread Pizza",
"Barbecue Flatbread Pizza",
"Greek Flatbread Pizza",
"Hawaiian Flatbread Pizza",
"Pepperoni Flatbread Pizza",
"Spanish Dancer Flatbread Pizza",
"White Pizza",
"Mozzarella Cheese Pizza",
"The Original Cellar Pita Pizza",
"White Pizza",
"Pizza Role",
"Pizza Role",
"Taco Pizza",
"The Classic Mexican Pizza",
"Pizza Slice",
"Whole Pizza",
"Whole Pizza Pie",
"Jr. Pepperoni Pizza",
"Pizza Sandwich",
"Pizza Stick",
"Mexican Pizza",
"Greek Pizza",
"Taco Pizza",
"B.b.q. Chicken Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Pepperoni Pizza",
"Roasted Vegetable Pizza",
"Spicy Meat Pizza",
"The Everything Pizza",
"Buffalo Chicken Pizza",
"House of Brews Breakfast Pizza",
"Smores Dessert Pizza",
"Pizza",
"Fajita Pizza",
"Max, S Pepperoni Pizza",
"Pazzo Pizza",
"Philly Cheese Pizza",
"Barbeque Chicken Pizza",
"Blt Pizza",
"Buffalo Chicken Pizza",
"Club Pizza",
"Deluxe Pizza",
"Hawaiian Ham Pizza",
"Pizza",
"Chinese Pizza",
"Breakfast Pizza",
"Pizza",
"The Original Bbq Chicken Pizza",
"The Original Bbq Chicken Pizza",
"White Pizza",
"Pizza",
"Pizza Sem Puce",
"Pizza Semplice",
"Barbecue Chicken Pizza",
"Cajun Chicken Pizza",
"Chicken Bacon Ranch Pizza",
"Classic Veggie Pizza",
"Garlicky Chicken Pizza",
"Lemon Pepper Chicken Pizza",
"Master Pizzas",
"Pizza Lunch Deal",
"Pizza Bianca",
"Pizza Del Giorno",
"Sushi Pizza",
"Cheese Pizza",
"Alfredo Pizza",
"Four Seasons Pizza",
"Margherita Pizza",
"Napoli Pizza",
"Pollo Special Pizza",
"Rustica Pizza",
"Seafood Pizza",
"White Pizza",
"Cheese Pizza",
"Cheese Stuffed Pizza",
"Barbecue Pizza",
"Meatball Pizza",
"Pizza Special",
"Pizza Steak",
"White Pizza, Four Cheeses, Garlic, Sprinkle of Oregano",
"Chicago Pizza",
"Prosciutto Pizza",
"Spinach Pizza",
"Wild Mushroom Pizza",
"Cheese Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Meal Buster Pizza",
"Meat Lovers Pizza",
"Pizza Burger Sub",
"Pizza Burger Sub",
"Pizza City Delight Pizza",
"Pizza Fries",
"Pizza Fries",
"Pizza Steak Sub",
"Pizza Steak Sub",
"Pizza Sub",
"Pizza Sub",
"Vegilicious Pizza",
"White Pizza",
"Pizza Margarita",
"Pizza Slices",
"Deluxe Pizza Subs",
"Pizza Subs",
"Cheese Pizza",
"Pizza Bread",
"Primavera Pizza",
"Buffalo Chicken Pizza",
"Pizza Hoagie",
"Margherita Pizza",
"Shrimp Pizza",
"Pizza Margherita",
"Pizza Margherita Combination",
"Pizza Prosciutto Con Arugula",
"Pizza Prosciutto Con Arugula Combination",
"Cheese Pizza",
"Pepperoni Pizza",
"Pizza Burger",
"Pizza Margherita",
"Medium Cheese Pizza",
"Chicken Bbq Pizza",
"Chicken Bbq Pizza",
"Chicken Wing Pizza",
"Pizza Bianca",
"Ranch Chicken Pizza",
"Fajita Pizza",
"Lone Star Bbq Pizza",
"Original Bbq Chicken Pizza",
"Philly Cheese Pizza",
"Sicilian Pizza",
"Ultimate Meat Pizza",
"Taco Pizza",
"Create Your Own Pizza",
"Veggie Pizza",
"Classic Cheese Pizza",
"Classic Cheese Pizza",
"Crispy Thin Cheese Pizza",
"Crispy Thin Cheese Pizza",
"Deep Pan Pizza",
"Deep Pan Pizza",
"Pizza Sub",
"Pizza Sub",
"Side of Pizza Sauce",
"Side of Pizza Sauce",
"Margherita Pizza Crepe",
"15 Pizza Fruitti Di Mare",
"15 Pizza Mafia",
"Bolognia Pizza",
"Milano Pizza",
"Roma Pizza",
"Pepperoni Pizza Fries",
"Pizza",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Pizza Steak Works",
"Pizza Turnovers",
"Build Your Own Pizza",
"Cheese Pizza",
"Margherita Pizza",
"Smoked Bbq Chicken Pizza",
"Vegetarian Pizza",
"Venison Sausage Pizza",
"Bianca Pizza",
"Jerry Special Pizza",
"Pizza By The Slice",
"Pizza By The Slice",
"Sicilian Pizza",
"Pizza Sticks",
"Parma Pizza",
"2 Large Pizzas",
"Chicken Bacon Ranch Pizza",
"Steak and Cheese Pizza",
"Unreal Pizza Deal",
"Mozzarella Cheese Pizza With Tomato Sauce",
"Veggie Lovers Pizza",
"Lobster Pizza",
"2 Large 14 Plain Pizza",
"2 Large Pizzas",
"Chicken Pizza Steak",
"One Jumbo Plain Tomato and Cheese Pizza",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Flatbread Pizza",
"Bbq Chicken Pizza",
"Pizza of The Day",
"Signature Pizza Slice of The Day",
"Barbecue Chicken Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Meat Lovers Pizza",
"Mediterranean Pizza",
"Philly Pizza",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Vegetarian Pizza",
"Pizza Burger",
"The Plain Big Cheese Pan Pizza",
"Chicken Scallopini Pizzaiola",
"Pita Pizza",
"Pizza With Chicken",
"Veal Scallopini Pizzaiola",
"Thin Crust Pizza",
"Cheese Pizza",
"Margherita Pizza",
"White Pizza",
"Gluten Free Pizza",
"Pizza Roll",
"Buffalo Chicken Pizza",
"Buffalo Chicken Sicilian Pizza",
"Cheese Pizza",
"Chicken Parmigiana Sicilian Pizza",
"Eggplant Parmigiana Sicilian Pizza",
"Margarita Sicilian Pizza",
"Pizza Fries",
"Pizza Steak",
"Pizza Turnover",
"Portabello Sicilian Pizza",
"Red Pizza",
"Regular Slice of Pizza",
"Round Pizza On A Wrap",
"Round Pizza On A Wrap",
"Sicilian Slice of Pizza",
"The Works Pizza",
"White Pizza",
"Build Your Own Breakfast Pizza",
"Build Your Own Pizza",
"Antonio Pizza",
"Cheese Pizza Slice",
"Edwardo Pizza",
"Pepperoni Pizza Slice",
"Prosciutto Pizza",
"Roman Pizza",
"Sicilian Pizza",
"White Pizza",
"Pizza Bread Slices",
"With Pizza Cheese",
"Italian Meat Lovers Pizza",
"Margherita Pizza",
"Apple Pizza",
"Bbq Pork Pizza",
"Bbq Pork Pizza",
"Bufalo Chicken Pizza",
"Cheese Lovers Pizza",
"Chicken Pesto Pizza",
"Four Season of Pizza",
"Four Season of Pizza",
"Fresh Greek Pizza",
"Italiano Four Seasons Pizza (quanttro Stagioni)",
"Italiano Four Seasons Pizza (quanttro Stagioni)",
"Margarita Pizza",
"Meat Lovers Pizza",
"Philly Style White Pizza",
"Philly White Chicken Pizza",
"Philly White Chicken Pizza",
"Pizza Bianca",
"Pizza Bolognese",
"Pizza Fugazza",
"Pizza Marinara",
"Pizza Melanzane",
"Positano Chicken Pizza",
"Positano Chicken Pizza",
"Primo Alfredo White Pizza",
"Primo Alfredo White Pizza",
"Santorini Pizza",
"Santorini Pizza",
"Shrimp Alfredo Pizza",
"Vegetarian Pizza",
"Vegetarian White Pizza",
"Vegetarian White Pizza",
"Veggie Ranch Pizza",
"White Pesto Pizza",
"White Pesto Pizza",
"White Pizza",
"Pizza Burger 6 Oz.",
"Pepperoni Pizza",
"Pizza Classics",
"Tuna Pizza",
"Margarita Pizza",
"Breakfast Pizza Slice",
"Pizza and Calzone Extras",
"Pizza Bread Slices",
"With Pizza Cheese",
"Pizza Fritta",
"Pizza Rolls",
"Pizza Sub",
"8in Mini Cheese Pizza",
"Garlic Pizza Bread",
"Pizza Sub",
"Blackened Chicken Pizza",
"Hawaiian Pizza",
"Pesto Chicken Pepperoni Pizza",
"Shrimp Asparagus Pizza",
"Pizza Puff",
"Alfredo Pizza",
"Buffalo Chicken Pizza",
"Chicken Alfredo Pizza",
"Fresh Mozzarella Pizza",
"Garlic Pizza",
"Greek Pizza",
"Margherita Pizza",
"Pizza By The Slice",
"Della Casa Pizza",
"Kids Pizza",
"Prosciutto Italiano Pizza",
"Wednesday Pizza Night",
"Dessert Pizza",
"Pizza",
"Taco Pizza",
"Pizza Omelette",
"Create Your Own Pan Pizza",
"Individual Pizza Event",
"One Large House Made Pizza Dough Ball,",
"Specialty Pizza Slice Event",
"Start With Our Cheese Pizza and Add Your Favorite Toppings",
"2 Large Cheese Pizza",
"2 Small Cheese Pizza",
"Whole Wheat Pizza",
"Naan Pizza",
"Smoked Salmon Naan Pizza",
"Cheese Pizza",
"White Pizza Special",
"Pizza Bread",
"Pizza Puff",
"Baked Ziti Pizza",
"Caprese Square Pizza",
"Chicken Parmigiana Pizza",
"Combo Pizza",
"Eggplant Parmigiana Pizza",
"Fresh Tomato Pizza",
"Hawaiian Pizza",
"Lasagna Pizza",
"Margherita Pizza",
"Marinara Square Pizza",
"Meat Lover Pizza",
"Mixed Vegetable Pizza",
"Pepperoni Square Pizza",
"Pizzas",
"White Pizza",
"White Pizza With Broccoli or Spinach",
"White Pizza With Broccoli Rabe",
"Naan Pizza 1",
"Naan Pizza 2",
"Naan Pizza 3",
"1 Large 1 Topping Pizza",
"Large Cheese Pizza",
"Large Cheese Pizza With One Topping",
"Large Supreme Pizza",
"Pizza Slice",
"Broccoli and Shells Pizza",
"Buffalo Chicken Pizza",
"Goat Cheese Pizza",
"Pepe Le Pizza",
"Pizza Ala Vodka",
"The Original Greek Pizza",
"Pizza A La Mexicana",
"Doughless Pizza",
"Main Street Pizza Sub",
"Specialty Pizzas",
"Thin Crust Mini Pizza",
"Dry Barrel Margherita Pizza",
"Platoon Pepperoni Pizza",
"Sausage Onion Jam Pizza",
"Kids Flatbread Pizza",
"Pancetta Egg Pizza",
"Caprese Pizza",
"Margarita Pizza",
"Pizza Bianca",
"Pizza Capriciosa",
"Pizza Margherita",
"Rotisserie Chicken Pizza",
"Veggie Pizza",
"White Pizza (pizza Bianca)",
"Greco Pizza (greek Pizza)",
"Pizza Bianco (white Pizza)",
"Veggie Pizza",
"Bacon Cheeseburger Pizza",
"Bbq Chicken Pizza",
"Bianca Pizza",
"California Club Pizza",
"Carne (meat) Pizza",
"Chicken, Bacon and Spinach Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"Lotti Cheese Pizza",
"Margarita Pizza",
"Mediterranean Pizza",
"Pesto Chicken Pizza",
"Pizzaa Burger",
"Supreme Pizza",
"Taco Pizza",
"Tomato Pie Pizza",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"All American Deep Dish Pizza",
"Cheese Pizza",
"Veal Pizzaiola",
"Pizza Del Giorno",
"Any Brick Oven Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Flatbread Pizza",
"Cheese Party Pizza",
"Cheese Pizza",
"Margherita Flatbread Pizza",
"Pizza Burger",
"Pizza Hero",
"Pizza Con Formaggio",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Cheeseburger Pizza",
"Philly Cheese Steak Pizza",
"Pizza Bread",
"Taco Pizza",
"Kids Cheese Pizza Meal",
"Flatbread Pizza, Caramelized Onion",
"Flatbread Pizza, Fresh Mozzarella",
"Buffalo Pizza",
"Falafel Pizza",
"Greek Grill Pizza",
"Gyro Pizza",
"Spinach Pie Pizza",
"Veggie Pizza",
"Decadent Chicken Pizza",
"Gourmet Meatball Pizza",
"Lunch Pizza Your Way",
"Ooey Gooey Pizza Pie",
"Roasted Vegetable and Goat Cheese Pizza",
"Starter Pizza",
"Sausage Onion Jam Pizza",
"Sausage Onion Jam Pizza",
"B.b.q. Chicken Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Pepperoni Pizza",
"Roasted Vegetable Pizza",
"Spicy Meat Pizza",
"The Everything Pizza",
"Pizza Con Formaggio",
"Artisan Cheese Pizza",
"Pepperoni or Cheese Pizza",
"Pepperoni or Cheese Pizza",
"Pizza",
"Specialty Pizzas",
"1 Ingredient Pizza",
"Cheese Thin Crust Pizza",
"Pan Cheese Pizza",
"Pan Cheese Pizza With One Ingredient",
"Pizza Bread",
"Stuffed Cheese Pizza",
"Stuffed Cheese Pizza With One Ingredient",
"Thin Crust Four Season Pizza",
"Thin Crust Hawaiian Pizza",
"Thin Crust Veggie Pizza",
"Sausage Onion Jam Pizza",
"Pizza Buffet",
"Specialty Pizzas",
"Nuevo Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Pizza Bomba",
"Pizza Margherita",
"Goat Cheese Pizza",
"Buffalo Chicken Pizza",
"Chicken Pizza Steak",
"Pizza French Fries",
"Pizza Steak",
"Sausage Onion Jam Pizza",
"Pesto Pizza",
"White Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza (large)",
"Bbq Chicken Pizza (medium)",
"Bbq Chicken Pizza (small)",
"Buffalo Chicken Pizza",
"Buffalo Chicken Pizza (large)",
"Buffalo Chicken Pizza (medium)",
"Buffalo Chicken Pizza (small)",
"Chicken and Broccoli Pizza",
"Chicken and Broccoli Pizza (large)",
"Chicken and Broccoli Pizza (medium)",
"Chicken and Broccoli Pizza (small)",
"Farmers Pizza",
"Farmers Pizza (large)",
"Farmers Pizza (medium)",
"Farmers Pizza (small)",
"Four Seasons Pizza",
"Four Seasons Pizza (large)",
"Four Seasons Pizza (medium)",
"Four Seasons Pizza (small)",
"Greek Pizza",
"Greek Pizza (large)",
"Greek Pizza (medium)",
"Greek Pizza (small)",
"Hawaiian Pizza",
"Hawaiian Pizza (large)",
"Hawaiian Pizza (medium)",
"Hawaiian Pizza (small)",
"Margarita Pizza (large)",
"Margarita Pizza (medium)",
"Margarita Pizza (small)",
"Meat Lovers Pizza",
"Meat Lovers Pizza (large)",
"Meat Lovers Pizza (medium)",
"Meat Lovers Pizza (small)",
"Potato and Broccoli Pizza",
"Potato and Broccoli Pizza (large)",
"Potato and Broccoli Pizza (medium)",
"Potato and Broccoli Pizza (small)",
"Sicilian Pizza",
"Sicilian Pizza (large)",
"Sicilian Pizza (medium)",
"Sicilian Pizza (small)",
"Summer Garden Pizza",
"Summer Garden Pizza (large)",
"Summer Garden Pizza (medium)",
"Summer Garden Pizza (small)",
"Taco Pizza",
"Taco Pizza (large)",
"Taco Pizza (medium)",
"Taco Pizza (small)",
"White Pizza",
"White Pizza (large)",
"White Pizza (medium)",
"White Pizza (small)",
"Mexican Pizza",
"Veggie Pizza",
"Pepperoni Pizza",
"Pizza",
"Pizza By The Slice",
"Taco Pizza",
"Vegetarian Pizza",
"Pizza Toppings",
"Premium Pizza Toppings",
"Caprese Pizza",
"Pizza Tomato Sauce Cheese Blend",
"White Pizza",
"Wild Thing Pizza",
"Build Your Own Pizza",
"Pizza Bloody Mary",
"Pizza Rolls",
"Prosciutto Bistro Pizza",
"Smoky Buffalo Chicken Pizza",
"Spicy Capicola Pizza",
"Spinach and Feta Pizza Rolls",
"Cheese Pizza",
"Pizza Burger",
"Pizza Roll Sub",
"Hand Tossed Brick Oven Pizza",
"Gluten Pizza",
"Kids Cheese Pizza",
"The Tommy Gun Breakfast Pizza",
"Cheese Flatbread Pizza",
"Pizza Special",
"Cheese Pizza",
"Pizza Fries",
"Pizza Logs",
"Pizza Sub",
"Taco Pizza",
"Sausage Onion Jam Pizza",
"Cheese Pizza",
"Meatball Pizza",
"Pizza Sub",
"Pizza Sub Deluxe",
"Pizza Sub Special",
"Taco or Chicken Taco Pizza",
"Pizza Burger",
"Flat Bread Pizza Margherita",
"Calabrese (pizza In A Pocket)",
"Build Your Own Pizza",
"White Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Traditional Pizza",
"Medium Cheese Pizza",
"White Pizza",
"Crooked Cheese Pizza",
"Crooked Pepperoni Pizza",
"Grilled Caesar Pizza",
"Grilled Margherita Pizza",
"Grilled Pepperoni Pizza",
"Two Slices of Plain Pizza",
"Pizza Roll",
"Artisan Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"New Yorker Pizza",
"Pizza Margherita",
"White Pizza",
"Pizza Burger",
"Pizza Lasagna",
"Classic Cheese Pizza",
"Crispy Thin Cheese Pizza",
"Deep Pan Pizza",
"Pizza Sub",
"Side of Pizza Sauce",
"Cheese Pizza",
"Cheese Pizza",
"Deluxe Pizza",
"Deluxe Pizza",
"Meat Lovers Pizza",
"Meat Lovers Pizza",
"Pepperoni Pizza",
"Pepperoni Pizza",
"Sausage Pizza",
"Sausage Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Individual Cheese Pizza",
"Cheese Pizza",
"Build Your Own Pizza",
"Cheese Pizza",
"French Bread Pizza",
"Gluten Free Veg Out Pizza",
"Pizza Base",
"Thai Dye Pizza",
"All White Pizza",
"Hawaiian Pizza",
"Lasagna Pizza",
"Lobster Pizza",
"French Bread Pizza",
"Large Cheese Pizza",
"Large Hawaiian Pizza",
"Large Meatlover Pizza",
"Large Pepperoni Pizza",
"Large Supreme Pizza",
"Large Veggie Pizza",
"Classic Cheese Pizza",
"Crispy Thin Cheese Pizza",
"Deep Pan Pizza",
"Pizza Sub",
"Side of Pizza Sauce",
"Chicken Fajita Pizza",
"Pizza Sticks",
"Chocolate Chip Pizza",
"Mexican Pizza",
"Buffalo Chicken Pizza",
"Cali Chicken Bacon Ranch Pizza",
"Fiery Hawaiian Pizza",
"Honolulu Hawaiian Pizza",
"Memphis Bbq Chicken Pizza",
"Pacific Veggie Pizza",
"Philly Cheese Steak Pizza",
"Pizza",
"Pizza Crusts",
"Wisconsin 6 Cheese Pizza",
"Margherita Pizza 6 Calamari Fritti",
"Cheese Pizza",
"Mini Pizza One Topping",
"Pizza Bread",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Bbq Chicken Pizza",
"Chicken Delight Pizza",
"Deluxe Pizza",
"Eggplant Delight Pizza",
"Garlic Chicken Pizza",
"Garlic Delight Pizza",
"Giant Cheese Pizza",
"Hawaiian Delight Pizza",
"Jumbo Cheese Pizza",
"Large Cheese Pizza",
"Margherita Pizza",
"Meat Eaters Pizza",
"Medium Cheese Pizza",
"Personal Cheese Pizza",
"Pesto Chicken Pizza",
"Veggie Alfredo Pizza",
"Veggie Pizza",
"White Knight Pizza",
"Hawaiian Pizza",
"Mexican Pizza",
"Pepperoni Pizza",
"Plain Cheese Pizza",
"Sausage Pizza",
"White Pizza",
"An Individual Classic Sirloin Pizza",
"An Individual Margherita Pizza",
"Classic Sirloin Pizza",
"Margherita Pizza",
"Pepperoni Mushroom Pizza",
"Pesto Chicken Pizza",
"Three Guys Pizza",
"Sausage Onion Jam Pizza",
"Pizza Bread",
"Pizza Special",
"Stuffed Pizza (add)",
"Taco Pizza",
"Pizza Burger W Fries",
"Pizza Steak",
"Cheese Pizza",
"Fig Pizza",
"Create Your Own Pizza",
"Pizza and Pitcher",
"Create Your Own Pizza",
"Chocolate Chunks Pizza",
"Pizza Delmar",
"Simply Pizza",
"Bbq Chicken Pizza",
"Blt Pizza",
"Grilled Margherita Pizza",
"Pepperoni Pizza",
"Vegetable Pizza",
"Pizza Sauce",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Cheese Pizza",
"Ham and Pineapple Pizza",
"Pepperoni Pizza",
"Pizza Al Pesto",
"Start With A Cheese Pizza",
"Pepperoni or Mushroom Pizza Burger",
"Pizza Rolls",
"White Pizza Thin",
"Pizza Steak",
"Slice of Cheese Pizza and Fries",
"Stuffed Pizza",
"Margherita Pizza",
"Pepperoni Mushroom Pizza",
"Pizza Di Parma",
"1 Topping Pizza",
"2 Toppings Pizza",
"3 Toppings Pizza",
"4 Toppings Pizza",
"Cheese Pizza",
"Prima Pizza",
"Pizza Sub",
"White Pizza",
"Americana Pizza Pocket",
"Flatbread Pizza",
"Italiano Pizza Pocket",
"Pizza Cheese Stix",
"100 Pound Pizza",
"Buffalo Chicken Pizza",
"Pizza By The Slice",
"Flat Bread Pizza of The Day",
"Bacon Cheese Fry Pizza",
"Bacon Cheeseburger Pizza",
"Bbq Chicken Pizza",
"Blazing Saddles Pizza",
"Blockhead Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Chicken Alfredo Pizza",
"Chicken Bacon Cheddar Pizza",
"Chicken Bacon Ranch Pizza",
"Chicken Cordone Bleu Pizza",
"Chili Cheese Fries Pizza",
"Cinnamon Dessert Pizza",
"Four Cheezer Pizza",
"French Canadian Pizza",
"Fried Chicken Pizza",
"Galore Pizza",
"Garden Pizza",
"Hawaiian Pizza",
"Heart Attack Pizza",
"High Plains Drifter Pizza",
"Massive Cheese Pizza",
"Maui Wowi Pizza",
"Mexican Pizza",
"Pepperoni Powerhouse Pizza",
"Philly Cheese With Beef Pizza",
"Philly Cheese With Chicken Pizza",
"Pizza Fries",
"Primavera Pizza",
"Run For The Border Pizza",
"Swiss Chalet Pizza",
"Teriyaki Chicken Pizza",
"Texas Ranger Pizza",
"Western Pizza",
"Whole Enchilada Pizza",
"Zingers Pizza",
"Italian Pizza Burger",
"Pizza Bites",
"Mexican Pizza",
"Mexican Pizza",
"Breakfast Pizza",
"Cheese Pizza",
"Greek Pizza",
"Pepper Bacon Pizza",
"Pepperoni Cheese Pizza",
"Prosciutto Pizza",
"Straight Up Junior Pizza",
"Bbq Chicken Pizza",
"Chesters Lavash Pizza",
"Bbq Chicken Pizza",
"Chicken Stuffed Pizza",
"Large Sicilian Cheese Pizza",
"New York Style Cheese Pizza Slice",
"Flat Bread Pizza",
"Pizza Bianca",
"Pizza Calabrese",
"Pizza Con Funghi E Taleggio",
"Pizza Con Prosciutto E Rucola",
"Pizza Con Salsiccia E Rapini",
"Pizza D.o.c.",
"Pizza De Uovo",
"Chinese Pizza",
"Pizza Roll",
"Bacon Cheese Burger Pizza",
"Bbq Grilled Chicken Pizza",
"Buffalo Chicken Pizza",
"Chicken Cordon Bleu Pizza",
"Chicken Special Pizza",
"Grilled Chicken Pizza",
"Hawaiian Pizza",
"Meat Lover Pizza",
"Mushroom Pizza Steak",
"Pepperoni Pizza Steak",
"Philly Traditional Steak Pizza",
"Pita Pizza",
"Pizza Burger",
"Pizza Fries",
"Pizza Skins",
"Pizza Steak",
"Supreme Pizza",
"Vegetable Pizza",
"2 Large Pizzas",
"All Meats Pizza",
"Eggplant Parmigiana Pizza",
"Extra Large Pizza",
"Pizza Burger",
"Pizza Cheese Steak",
"Pizza Fries",
"Sicilian Pizza",
"Spicy Shrimp Bruschetta Pizza",
"Tuscan Chicken Pizza",
"Pizza Con Formaggio",
"Personal Pan Pizza",
"Bbq Chicken Pizza",
"Hawaiian Pizza",
"Meat Lovers Pizza",
"Pizzas",
"The Dude Pizza",
"Pizza Bagel",
"1 Ingredient Pizza",
"Cheese Thin Crust Pizza",
"Pan Cheese Pizza",
"Pan Cheese Pizza With One Ingredient",
"Pizza Bread",
"Stuffed Cheese Pizza",
"Stuffed Cheese Pizza With One Ingredient",
"Thin Crust Four Season Pizza",
"Thin Crust Hawaiian Pizza",
"Thin Crust Veggie Pizza",
"Large Cheese Pizza",
"Pizza Burger",
"Pizza Fest",
"Small Cheese Pizza",
"White Pizza",
"Pizza Bread or Tomato Bread",
"All Meat Pizza",
"Buffalo Chicken Pizza",
"Canadian Chicken Pizza",
"Cashew Chicken Pizza",
"Chicago Combo Pizza",
"Cubs Pizza",
"Five Star Pizza",
"Garden Vegetable Pizza",
"Garlic Chicken Pizza",
"Hawaiian Chicken Pizza",
"Maui Chicken Pizza",
"Ragin Cajun Pizza",
"Tex Mex Pizza",
"The Chicago Fire Pizza",
"Vegetarian Pizza",
"Pita Plain Pizza",
"Pizza Boat",
"Regular Plain Pizza",
"Sicilian Square Pizza",
"White Pizza With Tomato",
"Baked Ziti Pizza",
"Bbq Chicken and Bacon Pizza",
"Brooklyn Style Pizza",
"Buffalo Chicken Pizza",
"Chicken Marsala Pizza",
"Chicken Pizzaiola",
"Chicken Pizzaiola (lunch Portion)",
"Deep Dish White Pizza",
"Gluten Free Pizza",
"Grandma Pizza",
"Meat Lovers Pizza (deep Dish)",
"Pizza Burger",
"Pollo Ala Vodka Pizza",
"White Pizza",
"Pizza of The Day",
"Cheese Flatbread Pizza",
"White Pizza (garlic, Ricotta, No Sauce)",
"Margarita Pizza",
"Slice of Pizza (cheese)",
"Slice of Pizza (special)",
"Carne Classica Pizza",
"Cinque Formaggio Pizza",
"Create Your Own Pizza",
"Create Your Own Pizza Large 18 Inches",
"Create Your Own Pizza Personal 12 Inches",
"Genovese Pesto Pizza",
"La Caponata Pizza",
"Margherita Pizza",
"Palermo Pizza",
"Portabella Mushroom Pizza",
"Portobello Mushroom Pizza",
"Taormina Pizza",
"Hawaiian Pizza",
"Taco Pizza",
"Veggie Pizza",
"Pizza Eggs Roll",
"Thin Crust Pizza",
"Veal Pizzaiola",
"Basil and Tomato Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Chicken Cacciatore Pizza",
"Chicken Pizza",
"Classic Pizza",
"Gorgonzola Pizza",
"Grilled Chicken Pizza",
"Hawaiian Pizza",
"Hot Sausage Pizza",
"Margherita Pizza",
"Meatball Pizza",
"Mozzarella Pizza",
"Pesto Pizza",
"Prosciutto Pizza",
"Scallop and Bacon Pizza",
"Shrimp and Artichoke Pizza",
"Shrimp and Broccoli Pizza",
"Shrimp Scampi Pizza",
"Steak and Cheese Pizza",
"Veggie Pizza",
"White Pizza (great For Kids)",
"White Pizza (great For Kids)",
"Pizza Del Giorno",
"Pizza Eggs Roll",
"Chesters Lavash Pizza",
"Any Six ( 6 ) 10 Signature Pizzas",
"Any Six (6) 10 Signature Pizzas",
"Gluten Free Pizza Available",
"Alfresco Pizza",
"Americano Pizza",
"Deluxe Pizza",
"Four Cheese Pizza",
"Gustosa Pizza",
"Margerita Pizza",
"Mediterranean Pizza",
"Fiamma Clams Casino Pizza",
"New York Style Pizza",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Whole Breakfast Pizza",
"Veggie Patch Pizza",
"Apple Delight or Cherry Jubilee Pizza",
"Large One Topping Pizza",
"Pizza",
"Pizza Double Deal",
"Western Steak Pizza",
"Chinese Pizza",
"1 Item Pizza",
"2 Item Pizza",
"3 Item Pizza",
"9. White Clam Pizza",
"Plain Cheese Pizza",
"Hot Wing Pizza",
"Sushi Pizza",
"Bbq Chicken Pizza",
"Cheesy Beef Pizza",
"Hawaiian Pizza",
"Meat Lovers Specialty Pizza",
"Stuffed Bbq Chicken Pizza",
"Stuffed Cheesy Beef Pizza",
"Stuffed Hawaiian Pizza",
"Stuffed Meat Lovers Pizza",
"Personal Size Pizza (cheese or Pepperoni)",
"Pizza Bread",
"Pizza Slices",
"White Pizza",
"Pizza Bread Slices",
"With Pizza Cheese",
"Brunch Pizza",
"Brunch Pizza",
"Pizza Al Uovo",
"Pizza Al Uovo",
"Pizza Bianco",
"Pizza Caprese",
"Pizza Carne",
"Pizza Margherita",
"Pizza of The Moment",
"Pizza Pollo",
"Build Your Own Pizza",
"Dessert Pizza",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Whole Breakfast Pizza",
"Mediterranean Pizza",
"Greek Supreme Pizza",
"Margherita Pizza",
"Mexican Pizza",
"Pizza Burger",
"Thincredible Thin Crust Pizza",
"Tuscan Pepperoni Pizza",
"5 Topping Special Pizza",
"Alfredo Pizza",
"Buffalo Pizza",
"Fresh Pizza Dough",
"Lg 1 Topping Pizza",
"Pizza By The Slice",
"Sicilian Pizza",
"Stuffed Pizza",
"Stuffed Pizza Slice",
"White Pizza",
"Berry Pizza",
"Cheeseburger Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Spicy Fennel Sausage Pizza",
"House Pizza Special",
"B.b.q. Chicken Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Pepperoni Pizza",
"Pizza Sushi",
"Roasted Vegetable Pizza",
"Spicy Meat Pizza",
"The Everything Pizza",
"Pizza Formaggi",
"Pizza Pepperoni",
"Nutella Pizza (8 Slices)",
"Pizza",
"Puglian Brunch Pizza",
"Tuscan Brunch Pizza",
"Wild Mushroom Brunch Pizza",
"Buffalo Chicken Pizza",
"Cali Chicken Bacon Ranch Pizza",
"Fiery Hawaiian Pizza",
"Honolulu Hawaiian Pizza",
"Memphis Bbq Chicken Pizza",
"Pacific Veggie Pizza",
"Philly Cheese Steak Pizza",
"Pizza",
"Pizza Crusts",
"Wisconsin 6 Cheese Pizza",
"Classic Coal Fire Pizza",
"Margarita Pizza",
"Pizza Burger",
"Cheese Pizza",
"Pepperoni Pizza",
"Veggie Pizza",
"Pizza",
"Daisy Pizza",
"Winter Pizza",
"Pizza Steak",
"Chicken Ranch Pizza",
"Newest Pizza In Town",
"Pizza",
"Pizzaburger",
"Bruschetta Pizza",
"Low Fat Specialty Pizza",
"Mani Pizzas",
"Margarita Pizza",
"Pizza Bianca",
"Roasted Pizza",
"White Pizza",
"Grandma Sicilian Pizza",
"Grandma Sicilian Pizza",
"Make It A Special Pizza",
"Make It A Special Pizza",
"Pizza",
"Tuna Pizza",
"Cheeseburger Pizza",
"French Bread Pizza",
"Vineyard Flat Bread Pizza",
"Zucchini Flat Bread Pizza",
"Pepperoni Pizza Skinz",
"Pizza Friez",
"Pizza Steak",
"White Pizza",
"White Pizza Deluxe",
"Chorizo Pizza",
"Fajita Pizza",
"Pepperoni Pizza",
"Sausage Pizza",
"Hawaiian Pizza",
"Mr. Potato Pizza",
"Mr. Shoes Philly Steak Pizza",
"Mr. Shoes White Pizza",
"New Chicken Wing Pizza",
"New Five Cheese Pizza",
"New Pizza Calamari",
"Pizza",
"Veggie Pizza",
"Ice Cream Pizza",
"Pizza Rolls",
"Hangover Pizza",
"Margherita Pizza",
"New York Strip Pizzaiola",
"Pizza Margherita",
"Primavera Pizza",
"Pizza Stick",
"Cheese Pizza",
"Nutella Pizza",
"Pizza",
"Pizza Biancha (no Sauce)",
"Ranch Bbq Chicken Pizza",
"Sicilian Square Party Tray Pizza",
"Includes Pizza Sauce and Mozzarella",
"Pizza Burger",
"Pizza Burger Melt",
"Pizza Margarita",
"Pizza Burger",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Pizza For Two",
"Taco Pizza",
"White Pizza",
"Pizza Con Carne",
"Big Fat Greek Pizza",
"Piggy In Heat Pizza",
"Rivertown Pizza",
"Thai Chicken Pizza",
"Vegetarian Pizza",
"Create Your Own Pizza",
"Gluten Free Pizza Calandra",
"Pizza Calandra",
"Pizza Con Carne",
"Pizza Contadina",
"Pizza Margherita",
"Pizza Mediterranean",
"Pizza Parmigiana",
"Pizza Pugliese",
"Pizzaiolla",
"Thin Crust Cheese Pizza",
"Thin Crust Pizza",
"Thin Crust Pizza Margherita",
"Thin Crust Pizza or Spaghetti",
"Pizza",
"Breakfast Pizza",
"Fajita Pizza",
"Lone Star Bbq Pizza",
"Original Bbq Chicken Pizza",
"Philly Cheese Pizza",
"Sicilian Pizza",
"Ultimate Meat Pizza",
"Margherita Pizza",
"Pub Pizza",
"Gluten Free Pizza",
"Greek Pizza",
"Pepperoni Pizza",
"Traditional Cheese Pizza",
"Veggie Pizza",
"Margherita Pizza",
"Cheese Pizza",
"Pizza Port Chronic Amber Ale",
"Pizza Port Chronicle",
"Pizza Port Chronicle Ale, Carlsbad, California, Usa (5.0)",
"Cheese Flatbread Pizza",
"Cheese Flatbread Pizza",
"Cheese Pizza",
"One Item Pizza",
"Pizza Dough",
"Stuffed Pizza",
"Three Item Pizza",
"Two Item Pizza",
"B.b.q. Madness Stuffed Pizza",
"B.b.q. Madness Stuffed Pizza",
"B.b.q. Madness Thin Crust Pizza",
"B.b.q. Madness Thin Crust Pizza",
"Bacon Cheeseburger Stuffed Pizza",
"Bacon Cheeseburger Stuffed Pizza",
"Bacon Cheeseburger Thin Crust Pizza",
"Bacon Cheeseburger Thin Crust Pizza",
"Bellablanca Gourmet Pizza (reg Crust)",
"Bellablanca Gourmet Pizza (reg Crust)",
"Bellablanca Gourmet Stuffed Pizza",
"Bellablanca Gourmet Stuffed Pizza",
"Bellablanca Thin Crust Pizza",
"Bellablanca Thin Crust Pizza",
"Blazin Buffalo Stuffed Pizza",
"Blazin Buffalo Stuffed Pizza",
"Blazin Buffalo Thin Crust Pizza",
"Blazin Buffalo Thin Crust Pizza",
"Cheese Stuffed Pizza",
"Cheese Stuffed Pizza",
"Cheese Thin Crust Pizza",
"Cheese Thin Crust Pizza",
"Fare Soldi Gourmet Pizza (reg Crust)",
"Fare Soldi Gourmet Pizza (reg Crust)",
"Fare Soldi Gourmet Stuffed Pizza",
"Fare Soldi Gourmet Stuffed Pizza",
"Fare Soldi Thin Crust Pizza",
"Fare Soldi Thin Crust Pizza",
"Hawaiian Gourmet Stuffed Pizza",
"Hawaiian Gourmet Stuffed Pizza",
"Hawiian Gourmet Pizza (reg Crust)",
"Hawiian Gourmet Pizza (reg Crust)",
"Hawiian Thin Crust Pizza",
"Hawiian Thin Crust Pizza",
"Meat Lover Gourmet Stuffed Pizza",
"Meat Lover Gourmet Stuffed Pizza",
"Mediterranean Gourmet Pizza (reg Crust)",
"Mediterranean Gourmet Pizza (reg Crust)",
"Mediterranean Gourmet Suffed Pizza",
"Mediterranean Gourmet Suffed Pizza",
"Mediterranean Thin Crust Pizza",
"Mediterranean Thin Crust Pizza",
"Pepperoni Stuffed Pizza",
"Pepperoni Stuffed Pizza",
"Pepperoni Thin Crust Pizza",
"Pepperoni Thin Crust Pizza",
"Sicilian Sweet Tooth Thin Crust Pizza",
"Sicilian Sweet Tooth Thin Crust Pizza",
"Siciliian Superman Stuffed Pizza",
"Siciliian Superman Stuffed Pizza",
"Sicillian Superman Thin Crust Pizza",
"Sicillian Superman Thin Crust Pizza",
"Sicillian Sweet Tooth Stuffed Pizza",
"Sicillian Sweet Tooth Stuffed Pizza",
"Vegetable Gourmet Pizza (reg Crust)",
"Vegetable Gourmet Pizza (reg Crust)",
"Vegetable Heaven Stuffed Pizza",
"Vegetable Heaven Stuffed Pizza",
"Vegetable Heaven Thin Crust Pizza",
"Vegetable Heaven Thin Crust Pizza",
"White Suicilian Stuffed Pizza",
"White Suicilian Stuffed Pizza",
"White Suicilian Thin Crust Pizza",
"White Suicilian Thin Crust Pizza",
"Pizza",
"Personal Cheese Pizza",
"Pizza",
"Pizza Boy Citra Pils (4)",
"Cal Italia Gold Medal Winner Food Network Pizza Champions Challenge",
"Margherita Winner World Cup Pizza, Cup, Naples, Italy",
"Pizza Campari",
"Pizza Capari",
"4 Cheese Pizzavegetarian Option",
"Bbq Pizzanew Item",
"Pizza Muffinsupick6 Favorite",
"Spaniko Pizza (wheat Crust)",
"Pan Pizza",
"Cheese Pizza",
"Garden Pizza",
"Hawaiian Pizza",
"Meat Munchers Pizza",
"Muncheez Bbq Chicken Pizza",
"Pizza Nugs",
"Spicy Hawaiian Pizza",
"Supreme Pizza",
"The Meatball Pizza",
"Artisanal Grilled Pizza",
"Grilled Pizza",
"Original Pizza Puff",
"Pizza Burger",
"Della Casa Pizza",
"Puttanesca Pizza",
"Bacon Cheeseburger Pizza",
"Baked Ziti Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"Nutella Pizza (sweet Pie)",
"Penne Ala Vodka Pizza",
"Shrimp Parmigiana Pizza",
"Sicilian Square Pizza",
"Steak and Cheese Pizza",
"Stuffed Meat Pizza",
"Stuffed Veggie Pizza",
"Taco Pizza",
"Vegetable Pizza",
"Pizza Special",
"Broccoli Rabe and Spicy Sausage Pizza",
"Create Your Own Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Prosciutto and Fig Pizza",
"Prosciutto Di Parma Pizza",
"Roasted Garlic and Sausage Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Create Your Own Pizza",
"Pizza Sandwich",
"Broccoli Pizza",
"Garlic Pizza",
"White Pizza",
"Pizza",
"Mini Pizza",
"Cheese Pizza",
"Chinese Pizza",
"Pizza Steak",
"Pizza Steak",
"Mangia Pizza Combo",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Cheese Pizza",
"Pizza Rolls",
"Pizza",
"Pizza Ricco",
"All Meat Pizza",
"Bacon Cheeseburger Pizza",
"Barbeque Pizza",
"Buffalo Chicken Pizza",
"Chicken Club Pizza",
"Hawaiian Pizza",
"Margherita Pizza",
"Taco Pizza",
"Vegetarian Pizza",
"Zesty Italian Pizza",
"Classic Cheese Pizza",
"Crispy Thin Cheese Pizza",
"Deep Pan Pizza",
"Pizza Sub",
"Side of Pizza Sauce",
"Chefs Daily Pizza",
"Happy Hour Pizza",
"Margherita Pizza",
"Prosciutto Rucola Pizza",
"Quattro Formaggi Pizza",
"Grilled Pizza",
"Pizza By The Slice",
"Cheese Pizza",
"Greek Pizza",
"Kiddie Pizza",
"Pizza Ai Funghi",
"Bbq Vegetarian Pizza",
"Caribbean Cajun Shrimp Pizza",
"Chicken Pizza",
"Fresh Tomato and Basil Pizza",
"Mushroom Pizza",
"Smoked Salmon Pizza",
"Flatbread Cheese Pizza",
"Kids Pizza",
"Cheese Pizza",
"Toss Up Pizza",
"Chicago 7 Pizza",
"Create Your Own Pizza",
"Double Deckeroni Pizza",
"Hawaiian Pizza",
"Royal Margherita Pizza",
"The Classic Pizza",
"Tuscan Chicken With Spinach Pizza",
"Cheese Pizza",
"Daily Pizza",
"Pizza Burger",
"Cheese Ice Cream Pizza",
"Supreme Ice Cream Pizza",
"Thin and Crispy Pizza (napolitano Style)",
"Tomato Sauce and Cheese (basic Pizza)",
"Veggie Pizza",
"White Pizza Bagel",
"Tuna Pizza",
"Pizza Margherita",
"White Pizza",
"Mexican Pizza",
"Margherita Pizza",
"Pizza Il Bosco",
"Pizza Margherita",
"Pizza Sopressata E Funghi",
"7 Inch Two Topping Pizza",
"7 Inch Two Topping Pizza",
"Brick Oven Pizza",
"Brick Oven Pizza",
"Pizza Alla Vodka",
"Pizza Alla Vodka",
"Cheese Pizza",
"Combination Pizza",
"Chicken Wing Pizza",
"Chicken Wing Pizza",
"Eggplant Ricotta Pizza",
"Eggplant Ricotta Pizza",
"Hawaiian Pizza",
"Hawaiian Pizza",
"Neapolitan Pizza",
"Neapolitan Pizza",
"Ricotta Cheese and Broccoli Pizza",
"Ricotta Cheese and Broccoli Pizza",
"Sicilian Pizza",
"Sicilian Pizza",
"Stuffed Pizza",
"Stuffed Pizza",
"The Palace Supreme Pizza",
"The Palace Supreme Pizza",
"Vegetarian White Pizza",
"Vegetarian White Pizza",
"White Garlic Pizza",
"White Garlic Pizza",
"Focaccia Pizza Bread",
"Grilled Chicken Pizza",
"Shrimp and Goat Cheese Pizza",
"Margherita Pizza",
"Margherita Pizza",
"Pizza or Calzone",
"Pizza or Calzone",
"Pizza Roll",
"Chicken Bacon Ranch Pizza",
"Chicken Bbq Pizza",
"Chicken Broccoli Aflredo Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"Margarita Pizza",
"Meat Lovers Pizza",
"Mediterranean Pizza",
"One Topping Cheese Pizza",
"Philly Cheesteak Pizza",
"Plain Cheese Pizza",
"Southern Pizza",
"Taco Pizza",
"Three Topping Cheese Pizza",
"Two Topping Cheese Pizza",
"Ultimate Buffalo Chicken Pizza",
"Vegetarian Pizza",
"Pizza Puff",
"Spicy Pizza",
"Pizza Blanca",
"Braised Beef Short Rib and Truffle Pizza",
"Buffalo Chicken Pizza",
"Margherita Pizza",
"Meat Lovers Pizza",
"Mushroom Pizza",
"Pepperoni Pizza",
"Red Clam Pizza",
"Roasted Garlic White Pizza",
"Sausage Pizza",
"Three Cheese White Pizza",
"3 Cheese Pizza",
"Bbq Chicken Pizza",
"Cheeseless Veggie Pizza",
"Pizza Cubana",
"Vegetable Pizza Bread Sandwich",
"Build Your Own Pizza",
"Cheese Pizza",
"Gluten Free Veg Out Pizza",
"Pizza Base",
"Thai Dye Pizza",
"Bar Pizza",
"Pizza Mexicana",
"Honey Blue Cheese Pizza",
"California Pizza",
"Personal Cheese Pizza",
"Barbeque Chicken Pizza",
"Buffalo Chicken Pizza",
"Pepperoni Pizza",
"Pesto Artichoke Pizza",
"Chicken Pita Pizza",
"Veggie Pita Pizza",
"Breakfast Hangover Pizza",
"Chorizo Sausage Pizza",
"Margarita Pizza",
"Pulled Pork Pizza",
"Mini 1 Topping Pizza",
"One Topping Pizza",
"Kids Size Pizza",
"Pizza",
"10 Sweep The Kitchen and 10 Single Topping Pizzas",
"12 Sweep The Kitchen Pizza",
"14 Party Pizza",
"14 Sweep The Kitchen Pizza",
"8 Single Topping Pizza",
"8 Sweep The Kitchen or Any 8 Specialty Pizza",
"Sweep The Kitchen Pizza",
"Veggie Pizza",
"Chipotle Pizza",
"Pizza Chefs Surprise of The Day",
"Tony Ronis Pizza Steak",
"Cheese Pizza",
"Pizza Al Fungi",
"Pizza Al Fungi",
"Pizza Alejo",
"Pizza Claudia",
"Pizza Margarita",
"Pizza Pepperoni",
"Pizza Primavera",
"Pizza Raviatta",
"Pizza Sausage",
"Yummy Honey Cheese Pizza",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Margherita Pizza",
"Mini Pizza",
"Pizzaetta",
"Cheese Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Pizza Del Giorno",
"Pizza Slice",
"Whole Pizza",
"Hawaiian Pizza",
"Chicken Parm Pizza",
"Pizza Burger",
"Pizza Steak Sandwich",
"Regular New York Style Pizza",
"Regularly New York Style Pizza",
"Slice of Stuffed Pizza",
"Stuffed Pizza",
"Taco Pizza",
"White Pizza",
"Bianca Large Pizza",
"Bianca Medium Pizza",
"Calabria Special Large Pizza",
"Calabria Special Medium Pizza",
"Calabria Special Sicilian Pizza",
"Cheese Large Pizza",
"Cheese Medium Pizza",
"Cheese Sicilian Pizza",
"Pizza Burger",
"Pizza Roll",
"Spinach Large Pizza",
"Spinach Medium Pizza",
"Vegetable Large Pizza",
"Vegetable Medium Pizza",
"Vegetable Sicilian Pizza",
"Cheese Pizza",
"Our Terrific Cheese Pizza",
"Personal Cheese Pizza",
"Personal Pepperoni Pizza",
"Pizza",
"Wild Mushroom Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Grandma Pizza",
"Pizza",
"Pizza Margherita",
"Sicilian Pizza",
"White Pizza",
"Pizza Sauce",
"Pizza Sub",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Apple Pizza",
"Hawaiian Pizza",
"Kids Pizza",
"Pizza A La Vodka",
"Pizza Bianca",
"Three Cheese Pizza",
"Cheese Pizza",
"Pizza Puffs",
"Pita Pizza Sandwich",
"Pizza Burger",
"Pita Pizza",
"Add To Large Pizzas",
"Any Large Pizza",
"Medium Pizza Offers",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Pizza Del Giorno",
"Grilled Bruschetta Pizza",
"Margherita Pizza",
"Bianco White Pizza",
"Pizza Margherita",
"B.b.q. Madness Stuffed Pizza",
"B.b.q. Madness Thin Crust Pizza",
"Bacon Cheeseburger Stuffed Pizza",
"Bacon Cheeseburger Thin Crust Pizza",
"Bellablanca Gourmet Pizza (reg Crust)",
"Bellablanca Gourmet Stuffed Pizza",
"Bellablanca Thin Crust Pizza",
"Blazin Buffalo Stuffed Pizza",
"Blazin Buffalo Thin Crust Pizza",
"Cheese Stuffed Pizza",
"Cheese Thin Crust Pizza",
"Fare Soldi Gourmet Pizza (reg Crust)",
"Fare Soldi Gourmet Stuffed Pizza",
"Fare Soldi Thin Crust Pizza",
"Hawaiian Gourmet Stuffed Pizza",
"Hawiian Gourmet Pizza (reg Crust)",
"Hawiian Thin Crust Pizza",
"Meat Lover Gourmet Stuffed Pizza",
"Mediterranean Gourmet Pizza (reg Crust)",
"Mediterranean Gourmet Suffed Pizza",
"Mediterranean Thin Crust Pizza",
"Pepperoni Stuffed Pizza",
"Pepperoni Thin Crust Pizza",
"Sicilian Sweet Tooth Thin Crust Pizza",
"Siciliian Superman Stuffed Pizza",
"Sicillian Superman Thin Crust Pizza",
"Sicillian Sweet Tooth Stuffed Pizza",
"Vegetable Gourmet Pizza (reg Crust)",
"Vegetable Heaven Stuffed Pizza",
"Vegetable Heaven Thin Crust Pizza",
"White Suicilian Stuffed Pizza",
"White Suicilian Thin Crust Pizza",
"Pizza Bismarck",
"Pizza Rima",
"Pizza Rustica Con Pancetta E Uova",
"Calmari Pizza",
"Chicken Pizzaiola",
"Genovese Pizza",
"Grandma Pizza",
"Veal Pizzaiola",
"Sushi Pizza (sake Signature Dish)",
"Cheese Pizza",
"Fru Fru Pizza",
"Margherita Pizza",
"Pepperoni Pizza",
"Pizza Bianca (without Tomato Sauce)",
"Pizza Margherita D. O. P.",
"Pizza Norcina (without Tomato Sauce)",
"Quattro Carne Pizza",
"Classic Pepperoni Pizza",
"Margherita Pizza",
"Bbq Pizza",
"Cheese Pizza",
"Taco Pizza",
"Cheese Pizza",
"Free Soft Drink With Pizza",
"Pizza Bread",
"Pizza Bread Deluxe",
"Pizza Burger",
"Pizza Burger Prima",
"Veggie Pizza",
"Margarita Pizza",
"Pizza",
"Pizza Burger",
"White Pizza",
"Mexican Pizza",
"Kids Pizza",
"Philly Chesse Steak Pizza",
"Taco Taco Pizza",
"Gluten Free Pizza",
"Pizza Sub",
"Sicilian Pan Pizza Includes",
"Pizza Margherita",
"Pizza Pepperoni",
"Build Your Own Pizza",
"Cheese Pizza",
"French Bread Pizza",
"Gluten Free Veg Out Pizza",
"Pizza Base",
"Thai Dye Pizza",
"Peter Pan Pizza",
"When You Were A Kid Pizza Burger",
"Cheese Pizza",
"Large Pizza (2 Toppings)",
"Pizza Sandwich",
"Bucks Pizza Stromboli",
"Build Own Pizza",
"Chicken Club Pizza",
"Greek Pizza",
"Margherita Pizza",
"Pizza",
"White Pizza",
"Pizza By The Slice (plain Cheese)",
"White Pizza",
"Broccoli Pizza",
"Capriccia Pizza",
"Greek Pizza",
"Moroccan Style Spicy Pizza",
"Pizza By The Slice",
"Trio Cheese Pizza",
"Tunisian Pizza",
"Vegan Pizza",
"Vegetarian Pizza",
"All Meat Pizza",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Vegetarian Pizza",
"Alpine Pizza",
"Alpine Pizza",
"Meat The Pizza Scramble",
"Paupers Pizza",
"Veggie Pizza Scramble",
"Sesame Seed Crusted Sashimi Grade Rare Tuna Pizza",
"Swiss Pizza",
"Pizza",
"Pizza Sarah",
"Tuna Pizza With Truffle Oil",
"Create Your Own Pizza",
"Pizza Fries",
"Flatbread Pizza",
"Cheese Pizza",
"Gourmet Pizza",
"Pizza Bagel",
"Greek Pizza",
"Pepperoni Pizza",
"Pizza Logs",
"Pizza Sub",
"Steak Pizza",
"White Pizza",
"Create Your Own Large Pizza",
"Create Your Own Small Pizza",
"Hot Oil Pizza",
"Hot Oil Pizza",
"Lomo Saltado Pizza",
"Lomo Saltado Pizza",
"10 Sweep The Kitchen and 10 Single Topping Pizzas",
"12 Sweep The Kitchen Pizza",
"14 Party Pizza",
"14 Sweep The Kitchen Pizza",
"8 Single Topping Pizza",
"8 Sweep The Kitchen or Any 8 Specialty Pizza",
"Sweep The Kitchen Pizza",
"Veggie Pizza",
"Pizza of The Day",
"2 Medium Cheese Pizza",
"Falafel Pizza",
"Mini Mediterranean Ground Beef Pizza",
"Pepperoni Pizza Fries",
"Pizza Burger",
"Pizza Fries",
"Pizza Steak",
"Sabatinos Pizza",
"Choose From Our Pizza Selections",
"Margherita Pizza",
"Pizza Capricciosa",
"Pizza Con Pollo E Pesto",
"Pizza Margarita",
"Pizza Margherita",
"Pizza Rustica Con Caprino",
"Pizza Rustica Con Caprino",
"Pizza Salmone",
"Pizza Salmone Affumicato",
"Pizza Salsiccia Piccante",
"Pizza Vegetariana",
"Pizza Vegitariana",
"Prosciutto Arugula Pizza",
"Sausage Onion Jam Pizza",
"Create Your Own Pizza",
"Pizza Americana",
"Pizza Steak",
"Chicken Pizza",
"Pizza Hero",
"Sicilian Pizza",
"White Pizza",
"Build Your Own Pizza",
"Cheesy Pita Pizza",
"Chicken Alfredo Pizza",
"Citiline Pizza",
"Fajita Pizza",
"Vegetrian Pizza",
"Pizza Logs (new)",
"Pizza By The Slice",
"Pizza Puffs",
"Pizza Sub",
"2 Slices of Pizza",
"Cheese Pizza",
"Stuffed Chicago Style Pizza",
"White Pizza",
"Pizza Steak Sandwich",
"Create Your Own Pizza",
"Pizza Cheese Steak",
"Pizza Fries",
"Mexican Pizza",
"1 Large 1, Topping Pizza",
"1 Large 1, Topping Pizza",
"1 Large Cheese Pizza",
"1 Large Cheese Pizza",
"1 Medium 1, Topping Pizza",
"1 Medium 1, Topping Pizza",
"1 Pizza With 2 Toppings",
"1 Pizza With The Works",
"1 Topping Pizza",
"1 Topping Pizza",
"Each 2nd Pizza",
"Each 2nd Pizza",
"Junior and Pizza With Mozzarella Cheese",
"Junior and Pizza With Mozzarella Cheese",
"Pizza Sub",
"Pizza Sub",
"Specialty Pizza",
"Specialty Pizza",
"Pizza Margherita",
"Pizza Schiacciata Alla Toscana",
"Margherita Pizza",
"Pepperoni Pizza",
"Pizza Sub",
"Cheese Pizza",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Autumn Squash Pizza",
"Seafood Pizza",
"Pizza",
"Fajita Pizza",
"Lone Star Bbq Pizza",
"Original Bbq Chicken Pizza",
"Philly Cheese Pizza",
"Sicilian Pizza",
"Ultimate Meat Pizza",
"Buffalo Chicken Pizza",
"Bacon Cheeseburger Pizza",
"Breakfast Pizza",
"Buffalo Chicken Wing Pizza",
"Chicken, Bacon, Ranch Pizza",
"Hawaiian Pizza",
"Honey Bbq Chicken Pizza",
"Pizza",
"Pizza Burger",
"Zesty Garlic Wing Pizza",
"Margarita Pizza",
"Pizza Bread",
"Palermo (our Signature Pizza)",
"Traditional Pizza",
"M S G Pizza",
"Pizza Pepe",
"Your Very Own Pizza",
"8 Pizza",
"Bbq Chicken Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"Manhattan White Pizza",
"Manhattan Works Pizza",
"Meat Lovers Pizza",
"Napoli Pizza",
"Pizza Bread (1 Topping)",
"Teriyaki Chicken Pizza",
"Veggie Lovers Pizza",
"Pizza Alfredo",
"Margherita Pizza",
"Pizza La France",
"Pizza Margherita",
"Pizza Palermo",
"Pizza Prosciutto",
"Pizza Sorrento",
"Mexican Pizza",
"Pizza Bread",
"Pizza Nova Special",
"Pizza Puff",
"Vegetarian Pizza",
"Flat Bread Pizza",
"Build Your Own Pizza",
"Create Your Own Pizza",
"Pizza",
"Cheese Pizza",
"Chicken Ranch Pizza",
"Garden Pizza",
"Kids Mini Pizza",
"Pizza Sub",
"Seafood Pizza",
"Veggie Pizza",
"Pizza of The Day",
"Pizza Burger",
"Pizza Fries",
"Buffalo Chicken Pizza",
"Chorizo and Pepper Pizza Fire Grilled Pizza Crust",
"Fresh Mozzarella and Tomato Pizza",
"Pizza Rustico",
"The Pizza Steak",
"Bbq Chicken Pizza Bread",
"Bbq Chicken Pizza Bread",
"Buffalo Chicken Pizza",
"Meatball Pizza",
"Mexican Pizza",
"Philly Cheese Steak Pizza",
"Pizza Bread",
"Sicilian Pizza",
"Panini Alla Pizza",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Whole Breakfast Pizza",
"Taco Pizza",
"Pizza Bread",
"Pizza Puff",
"Pizza Slices",
"Fajita Pizza",
"Lone Star Bbq Pizza",
"Original Bbq Chicken Pizza",
"Philly Cheese Pizza",
"Sicilian Pizza",
"Ultimate Meat Pizza",
"3 Cheese Pizza",
"Bbq Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Musaka Pizza",
"Philly Cheesesteak Pizza",
"S.m.o.g. Pizza",
"Mexican Pizza",
"Prosciutto Roasted Mushroom Pizza",
"Pizza Burger",
"Pizzaburger",
"Montville Inn Pizza",
"Spicy Shrimp Pizza",
"Combination Pizza (extra Large 28 Pieces)",
"Combination Pizza (large 20 Pieces)",
"Combination Pizza (medium 16 Pieces)",
"Combination Pizza (party Size 36 Pieces)",
"Combination Pizza (personal Size)",
"Combination Pizza (small 8 Pieces)",
"Personal Pizza",
"Veggie Pizza (extra Large 28 Pieces)",
"Veggie Pizza (large 20 Pieces)",
"Veggie Pizza (medium 16 Pieces)",
"Veggie Pizza (party Size 36 Pieces)",
"Veggie Pizza (personal Size)",
"Veggie Pizza (small 8 Pieces)",
"Large Cheese Pepperoni Pizza",
"Meatball or Chicken Parm Pizza",
"Meatball or Chicken Parm Pizza",
"Party Cheese Pepperoni Sheet Pizza",
"Pizza",
"Pizza Logs",
"Pizza Slice",
"White Pizza",
"2 Medium Pizzas",
"Cheese Pizza",
"Gourmet Meat Pizza (medium)",
"Gourmet Meat Pizza (small)",
"Medium Gourmet House Pizza",
"Medium Pizza",
"Pizza Shell",
"Small Pizza",
"White Pizza (medium)",
"White Pizza (small)",
"Pizza Burger",
"Breakfast Pizza",
"Buffalo Chicken Pizza",
"Cheese Pan Pizza",
"Deep Dish Cheese Pizza",
"Stuffed Cheese Pizza",
"Thin Crust Cheese Pizza",
"Any Brick Oven Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Flatbread Pizza",
"Cheese Party Pizza",
"Cheese Pizza",
"Pepperoni Pizza",
"Cheese Pizza",
"Pizza Bread",
"Steak Pizzaola",
"Blt Pizza",
"Pizza",
"Pizza of The Week",
"Grilled Pizza of The Day",
"Sirloin Steak Pizzaiola",
"French Bread Pizza",
"Pizza Bagel",
"Pizza Calzones",
"Bianca Pizza (no Sauce)",
"Creat Your Own Pizza",
"Pizza Roll",
"Pizza Role",
"Breakfast Pizza",
"Italian Sausage Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Roma Tomatro Basil Pizza",
"Special Neapolitan Pizza",
"Special Sicilian Pizza",
"Pizza",
"Sicilian Pizza",
"White Pizza",
"Veggie Pizza",
"Veggie Pizza Wrap",
"Gnocchi Bella Pizza",
"Insalata Bella Pizza",
"Pizza",
"Pizza Hogie",
"H.l.d. Pizza",
"Hawaiian Pizza",
"Pizza Boat",
"Tuna Pizza",
"Kid Pizza Bites",
"Italian Pepperoni Four Cheese Pizza",
"Margherita Pizza",
"Newcastle Bbq Chicken Pizza",
"Pepperoni, Spicy Sausage Prosciutto Pizza",
"Toscano Italian Pizza",
"Build Your Own Pizza",
"Nightly Pizza Special",
"Cajun Pizza",
"Sicilian Pizza",
"Vegetarian Pizza",
"Pizza Combo",
"Bbq Pizza",
"Cheese Pizza",
"Pepperoni Pizza",
"Cheese Pizza",
"Hawaiian Pizza",
"Pizza Fries",
"Pizza Sandwich",
"Veggie Pizza",
"Cheese Pizza",
"Livingwell Pizza",
"Portobello Pizza",
"Bacon Double Cheese Burger Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Cherry Pie Pizza",
"Chocolate Pizza",
"Coconut Cream Pizza",
"Create Your Own Pizza",
"Dutch Apple Treat Pizza",
"Hawaiian Pizza",
"Meat Market Pizza",
"Meat Sicilian Pizza",
"Sampler Pizza",
"Superoni Pizza",
"The Alfredo Pizza",
"The Torch Pizza",
"Vegetarian Sampler Pizza",
"Veggie Sicilian Pizza",
"Buffalo Chicken Pizza",
"Cheesesteak Pizza",
"Hawaiian Pizza",
"Veggie Pizza",
"White Pizza",
"Flatbread Cheese Pizza",
"Breakfast Pizza Slice",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Cheese Pizza",
"Mini Pizza Bites",
"Mini Pizza Bites",
"Pizza By The Slice",
"Pizza By The Slice",
"Specialty Pizza",
"Specialty Pizza",
"Whole Breakfast Pizza",
"Whole Breakfast Pizza",
"Cheese Pizza",
"Pizza",
"Mini Pizza",
"Pizza Angelina",
"Pizza Bianca",
"Pizza Funghi",
"Pizza Margherita",
"Pizza Marinara",
"Pizza Napoletana",
"Pizza Occhio Di Bue",
"Pizza Ortolana",
"Pizza Polpettine",
"Pizza Salame Piccante",
"Pizza Salsiccia",
"Pizza Bagel",
"Cheese Pizza (red or White)",
"Pizza Toppings",
"Buffalo Pizza",
"Cheese Grilled Pizza",
"Pesto Pizza",
"Spinach Pie Pizza",
"T. D. Pizza",
"Twice Baked Potato Pizza",
"Margherita Pizza",
"Mozzarella Organic Tomato Pizza",
"Smokehouse Pizza",
"Vegetarian Pizza",
"Cheese Flatbread Pizza",
"Pizza Alpina",
"Pizza Caprese",
"Pizza Di Estate Dal Forno A Legna",
"Pizza Gorgonzola",
"Pizza Zucca",
"Build Your Own Pizza",
"Cheese Pizza",
"Gluten Free Veg Out Pizza",
"Pizza Base",
"Thai Dye Pizza",
"Caprice Pizza",
"Chicken Broccoli Pizza",
"Hawaiian Pizza",
"Mexican Pizza",
"Philly Steak Pizza",
"Pizza Toppings",
"Primavera Pizza",
"Seafood Pizza Supreme",
"White Pizza",
"Carne Alla Pizzaiola",
"Pizza Della Nonna",
"Barbecue Chicken Pizza",
"Carolina Goat Cheese Pizza",
"Cheese Pizza",
"Chicken Meatball Pizza",
"Margherita Pizza",
"Oven Roasted Vegetable Pizza",
"Pepperoni Pomodoro Pizza",
"Prosciutto Pizza",
"Pucks Pizza",
"Roasted Wild Mushroom Pizza",
"Spicy Shrimp Pizza",
"Sweet Fennel Sausage Pizza",
"Caprese Pizza",
"Pizza",
"Pizza Marinara",
"Pizza Primavera",
"Pizza Rolls",
"Pizza Toppings",
"Sorrentino Pizza",
"Specialty Pizza Toppings",
"Spinach Pizza",
"White Pizza",
"Cheese Pizza",
"Pizza",
"Pizza Pocket",
"Any Lg Pizza Up To 4 Toppings",
"Any Med Pizzas Up To 4 Toppings",
"Pizza Fries",
"Pizza Sauce",
"Square 1 Topping Pizza",
"Charbroiled Chicken Pizza",
"Frickin Chicken Pizza",
"Mississippi Bbq Pizza",
"Pizza Bagel",
"Pizza Bread",
"Breakfast Pizza",
"Flat Bread Pizza (7x7)",
"Pizza",
"Creat Your Own Pizza",
"All Pizzas",
"Build Your Own Pepperoni Pizza",
"Classic Margherita Pizza",
"Fennel Sausage Pizza",
"Peperoncini Pizza",
"Thyme Roasted Mushroom Pizza",
"Four Cheese Pizza",
"Greek Pizza",
"Pizza Luau",
"Start With Our Pizza Margherite",
"Pizza Burger",
"Pizza Burger",
"Hawaiian Pizza",
"Pizza Margarita",
"Pizza Margherita",
"Pizza Polpo",
"Buffalo Chicken Pita Pizza",
"Cheese Pizza",
"Buffalo Chicken Pizza (white)",
"Margherita Pizza (white)",
"Veggie Pizza (tomato)",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Bbq Chicken Pizza",
"Breakfast Pizza",
"Breakfast Pizza",
"Chicken Florentine Pizza",
"Chipotle Shrimp Pizza",
"Pepperoni or Cheese Pizza",
"Pizza Rustico",
"Short Rib Pizza",
"Spicy Italian Sausage Pizza",
"Steak Pizza",
"Wild Mushroom Pizza",
"Pizza Burger",
"Chicken, Spinach Bacon Pizza",
"Margherita Pizza",
"Pepperoni Classica Pizza",
"Prosciutto Fennel Pizza",
"Sicilian Pizza",
"Chicken Pita Pizza",
"Veggie Pita Pizza",
"Sushi Pizza",
"Cheese Pizza",
"Cheese Pizza Slice",
"One Topping Cheese Pizza",
"Sicilian Pizza Slice",
"Two Topping Cheese Pizza",
"Bulgogi Tortilla Pizza",
"Franks Buffalo Chicken Pizza",
"Pizza Bread Slices",
"With Pizza Cheese",
"Tuna Sushi Pizza",
"American Pizza",
"Apple Pie Pizza",
"Berkeley Vegan Cheese Veggie Pizza",
"California Pizza",
"Casablanca Pizza",
"Cheese Pizza",
"Greek Pizza",
"Italian Pizza",
"Mexican Pizza",
"Napoli Pizza",
"Provence Pizza",
"Santa Fe Pizza",
"Thai Pizza",
"Tuscan Mushroom Pizza",
"Zbq Pizza",
"White Pizza",
"Pizza Puffs",
"Pizza Steak",
"Pizza Turnover (baked)",
"Pita Pizza",
"Pepperosa Pizza",
"Island Pizza",
"Any Brick Oven Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Flatbread Pizza",
"Cheese Party Pizza",
"Cheese Pizza",
"Margherita Flatbread Pizza",
"Small Specialty Pizzas",
"Assorted Pita Pizzas",
"Yiayias Pizza",
"Sushi Pizza",
"8 Corner Pizza",
"Pizza",
"Pizza Sauce",
"Flat Bread Pizza of The Day",
"Custom Build Pizza",
"White Pizza",
"Buffalo Chicken Pizza",
"Margarita Pizza",
"Pepperoni Pizza",
"Philly Cheesesteak Pizza",
"Veggie Pizza",
"Cheese Pizza",
"Thin Crust Pizza",
"Raw Pizza",
"Breakfast Pizza Slice",
"Cheese Pizza",
"Mini Pizza Bites",
"Pizza By The Slice",
"Specialty Pizza",
"Whole Breakfast Pizza",
"5 Borough Pizza",
"Bourbon Bbq Gourmet Pizza",
"Bowery Queen Pizza",
"Chicken Pesto Gourmet Pizza",
"Clams Casino Pizza",
"Hawaiian Pizza",
"Jerk Gourmet Pizza",
"Lobster Pizza",
"Margherita Pizza",
"Spicy Buffalo Gourmet Pizza",
"Ultimate Pepperoni Pizza",
"Veggie Pizza",
"Pizza Positano (large Only)",
"Sexy Pizza (xl Only)",
"Pizza Bread",
"Kids Pizza",
"Baked Pizzaiola",
"Cheesesteak Pizzaiola",
"Chicken Cheesesteak Pizzaiola",
"Pizza Burger",
"Pizza Fries",
"Traditional Pizzas",
"Family Pizza Nights",
"Pizza and Hoagies",
"Two Pizza Deal",
"Pizza Steak",
"Bbq Chicken and Red Onion Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Chicken Parmesan Pizza",
"Eggplant Pizza",
"Greek Pizza",
"Hawaiian Pizza",
"Linguica and Onion Pizza",
"Shrimp Scampi Pizza",
"Fried Pizza",
"Traditional Neapolitan Pizza",
"Large Pizza Buns",
"Personal Pizza",
"Pita Pizza",
"Pizza Bake",
"Pizza Bianca",
"Slice of Pizza When Available",
"Buffalo Wing Pizza",
"Garden Pizza",
"Hawaiian Pizza",
"Large Pizza 16 Inches",
"Margarita Pizza",
"Meat Pizza",
"Pan Pizza 16 Inches",
"Pizza Panini",
"Pizzaburger",
"Romano Pizza",
"Scampi Pizza",
"Sicilian Pizza 16 Inches",
"Pizza Al Funghi",
"Pizza Al Prosciutto",
"Pizza Con Fiore Di Zucca",
"Pizza Con Gamberi",
"Pizza Margherita",
"Pizza Classica",
"Breakfast Pizza",
"Butternut Squash Pizza",
"Plain Pizza",
"Prosciutto Pizza",
"2 Slices of Cheese Pizza and Medium Drink",
"New White Pizza",
"New York Pizza",
"Pizza Sandwich",
"Pizza Sandwich and Medium Drink",
"Veggie Pizza",
"Build Your Own Pizza",
"Build Your Own Pizza",
"Pizza Pesto",
"Flatbread Pizza",
"Sausage Onion Jam Pizza",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Veggie Patch Pizza",
"Crab Dip Pizza",
"Pita Pizza",
"Pizza By The Slice",
"Pizza By The Slice",
"Pizza Fries",
"Pizza Steak",
"Pizza Sub",
"Pizzaburger",
"Blackened Chicken Bacon Pizza",
"Pizza Caprese",
"Pizza Chevre",
"Pizza Marguerite",
"Individual Margarita Pizza",
"Individual Pepperoni Pizza",
"Shrimp Scampi Pizza",
"Pizza Burger",
"Pizza Burger",
"Pizza Logs",
"Pizza Sub",
"Mexican Pizza",
"Tuna Pizza",
"Build Your Own Pizza",
"Cheese Pizza",
"Egg Pancetta Pizza",
"French Bread Pizza",
"Fun Guy Pizza",
"Gluten Free Veg Out Pizza",
"Individual Pizza",
"Melchacho Pizza",
"Pizza Base",
"Thai Dye Pizza",
"Extra Pizza Cheese",
"Pizza Bianco",
"Sunny Side Up Farm Egg Pizza",
"Chicken, Spinach Bacon Pizza",
"Margherita Pizza",
"Pepperoni Classica Pizza",
"Pizza Bravo",
"Prosciutto Fennel Pizza",
"Sicilian Pizza",
"Margherita Pizza",
"Mexican Pizza",
"Cheese Pizza",
"Pepperoni Cheese Steak Pizza",
"Pork Bbq Pizza",
"Spinach Artichoke Pizza",
"White Pizza",
"2 Slices Cheese Pizza and Beverage",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Customer Appreciation Large Cheese Pizza",
"Pizza By The Slice",
"White Pizza",
"1 Topping Mozzarella Pizza",
"2 Topping Mozzarella Pizza",
"3 Topping Mozzarella Pizza",
"Hawaiian Gourmet Pizza",
"Margherita Gourmet Pizza",
"Mexican Pizza",
"Mozzarella Pizza",
"Pizza Burger Deluxe",
"Quinnipiac Pizza",
"Pizza",
"Sushi Pizza",
"Pizza",
"Pizza Deluxe",
"Bbq Chicken Pizza",
"Bbq Chicken Pizza",
"Buffalo Chicken Pizza",
"Cheese Pizza",
"Deluxe Pizza",
"Florentine Pizza",
"Individual Cheese Pizza",
"Individual Cheese Pizza Soup Sandwich Combo",
"Italian Beef Pizza",
"Kids Pizza",
"Mega Meat Pizza",
"Wednesday Pizzas",
"Pita Bread Cheese Pizza",
"Pizza Sub",
"Pizza",
"Cheese Pizza",
"Cheese Pizza",
"Pepperoni or Sausage Pizza",
"The New Yorker Party Pizza",
"Pizza Margherita",
"Pizza Marinara",
"Pizza Dora",
"Pizza Vongole",
"Cheese Pizza",
"Four Cheese Pizza",
"No Dough Pizza",
"Personal Pizza",
"Pita Pizza",
"Pizza Blanca",
"Chicago Deep Dish Pizza",
"Pizza Topping Dippers",
"Pizza Bianca",
"Pizza Fresca",
"Pizza Piccante",
"Sicilian Style (thick Crust Pizza)",
"Pastis De Pizza",
"Quesadillas (mexican Pizza)",
"All Meats Pizza",
"Margherita Pizza",
"Supreme Pizza",
"The New Yorker Pizza",
"Personal Pizza",
"Pizza Pizza",
"Bbq Pulled Pork Pizza",
"Bbq Pulled Pork Pizza",
"Greek Pizza",
"Pepperoni Pizza",
"Shrimp Creole Pizza",
"Supreme Pizza",
"Vegetarian Pizza",
"Pita Pizza",
"Steak Pizzaiola",
"White Pizza"]
const fs = require('fs');
const imagesFolder  = `/home/siddrc/5.WBS/github.com/nodejs-apps/images`

async function execute(){
  const pizzas = []
  const images = []
  fs.readdirSync(imagesFolder).forEach(file => {
        images.push(file)
  });
  pizzaNames.forEach((pizzaName,index)=>{
    const image = images[Math.floor(Math.random()*images.length)]
    const pizza = {
        
        name:pizzaName,
        image,
        pricesAndSizes:[{
          
          size:sizes[0],
          price:prices[Math.floor(Math.random()*prices.length)]
        },{
          
          size:sizes[1],
          price:prices[Math.floor(Math.random()*prices.length)]
        },{
          
          size:sizes[2],
          price:prices[Math.floor(Math.random()*prices.length)]
        }
      ]
    }
      pizzas.push(pizza)
  })
  try{
    const connection = await connect()
    connection.getRepository(pizzaEntity).save(pizzas)
  }catch(e){
    console.error(`[ERROR]:: ${e.message}-${e.stack}`)
  }
}

module.exports = {
    execute
}

